import {randomUUID} from 'node:crypto';
import {distance} from '../../image-prototype/core.js';
import {ITEMS,profile,stats,gainXp,promotionSkillLearned,basicAttackDelay,skillCastDelay,skillMpCost} from '../../image-prototype/catalog.js';
import {MATERIALS,RECIPES,ZONES,TRAVEL_PORTALS,DAILY_TASKS,PROMOTIONS,koreaDay,NAMED,bossWindow} from '../../image-prototype/mmo-data.js';
export const NODES=[
 {id:'wood1',material:'wood',x:390,y:780,zone:'surface',cooldown:60},{id:'wood2',material:'wood',x:1110,y:925,zone:'surface',cooldown:60},{id:'stone1',material:'stone',x:410,y:1320,zone:'surface',cooldown:90},{id:'ore1',material:'ore',x:1120,y:1740,zone:'surface',cooldown:120},
 {id:'woodG1',material:'wood',x:390,y:840,zone:'grove',cooldown:55},{id:'woodG2',material:'wood',x:1120,y:1270,zone:'grove',cooldown:55},{id:'stoneG',material:'stone',x:420,y:1740,zone:'grove',cooldown:80},{id:'oreG',material:'ore',x:1080,y:1870,zone:'grove',cooldown:110},
 ...['cave','ruins','abyss','celestial'].flatMap((zone,i)=>[
  {id:'crystal'+i+'a',material:'crystal',x:405,y:860,zone,cooldown:600},
  {id:'crystal'+i+'b',material:'crystal',x:1110,y:1370,zone,cooldown:600},
  {id:'crystal'+i+'c',material:'crystal',x:520,y:1810,zone,cooldown:600}
 ])
];
export function daily(p,now){if(p.state.daily?.day!==koreaDay(now))p.state.daily={day:koreaDay(now),hunt:0,gather:0,dungeon:0,claimed:[]};return p.state.daily;}
export function progress(w,p,key,n=1){const d=daily(p,w.now());d[key]=Math.min(DAILY_TASKS[key].goal,d[key]+n);}
function clearMotion(p){p.navPath=[];p.input={x:0,y:0};p.auto=false;p.autoTarget=null;p.combatTarget=null;p.combatSkill=-1;p.attackTarget=null;p.attackSkill=-1;p.attackUntil=0;}
function same(a,b){return a&&b&&a.channel===b.channel&&a.state.zone===b.state.zone;}
function close(a,b){return same(a,b)&&distance(a.state,b.state)<=220;}
export function initSystems(w){w.trades=new Map();w.duels=new Map();w.nextSocial=new Map();}
export function socialId(w,p){return [...w.trades.values()].find(t=>t.players.includes(p.id))||[...w.duels.values()].find(t=>t.players.includes(p.id));}
export function removeSocial(w,p){for(const map of [w.trades,w.duels])for(const [id,t] of map)if(t.players.includes(p.id)){map.delete(id);for(const pid of t.players){const q=w.players.get(pid);if(q)w.event(q,'거래 또는 대련이 취소되었습니다.');}}}
function invite(w,p,data,duel){const q=w.players.get(data.player);if(!q||q===p||!close(p,q)){w.event(p,'같은 지역의 가까운 유저를 선택하세요.');return;}if(socialId(w,p)||socialId(w,q)||p.exchangeBusy||q.exchangeBusy){w.event(p,'진행 중인 거래·대련을 먼저 끝내세요.');return;}if((w.nextSocial.get(p.id)||0)>w.now()){w.event(p,'초대는 10초마다 보낼 수 있습니다.');return;}if(duel&&(p.state.y>590||q.state.y>590)){w.event(p,'PVP 대련은 안전한 마을에서 시작하세요.');return;}const id=randomUUID(),t={id,players:[p.id,q.id],from:p.id,accepted:false,expires:w.now()+60,offers:{[p.id]:{gold:0,items:[],materials:{}},[q.id]:{gold:0,items:[],materials:{}}},confirmed:[]};(duel?w.duels:w.trades).set(id,t);w.nextSocial.set(p.id,w.now()+10);clearMotion(p);clearMotion(q);w.event(q,p.name+(duel?'님이 PVP 대련을 신청했습니다.':'님이 거래를 신청했습니다.'));}
function validOffer(p,o){if(!Number.isSafeInteger(o.gold)||o.gold<0||o.gold>p.state.gold||!Array.isArray(o.items)||o.items.length>8)return false;const counts={};for(const id of o.items){if(!Object.hasOwn(ITEMS,id)||id==='training'||id==='glowing')return false;counts[id]=(counts[id]||0)+1;if(counts[id]>p.state.bag.filter(x=>x===id).length-(Object.values(p.state.equipment).includes(id)?1:0))return false;}for(const [k,n] of Object.entries(o.materials||{}))if(!Object.hasOwn(MATERIALS,k)||!Number.isSafeInteger(n)||n<0||n>p.state.materials[k])return false;return true;}
async function settle(w,t){const [a,b]=t.players.map(id=>w.players.get(id));if(!t.accepted||!close(a,b)||a.exchangeBusy||b.exchangeBusy||!validOffer(a,t.offers[a.id])||!validOffer(b,t.offers[b.id])){w.trades.delete(t.id);if(a)w.event(a,'보유품·거리 변화로 거래가 취소되었습니다.');if(b)w.event(b,'보유품·거리 변화로 거래가 취소되었습니다.');return;}const aa=structuredClone(a.state),bb=structuredClone(b.state);for(const [p,q] of [[aa,bb],[bb,aa]]){const i=p===aa?a.id:b.id,o=t.offers[i];p.gold-=o.gold;q.gold+=o.gold;for(const item of o.items){p.bag.splice(p.bag.indexOf(item),1);q.bag.push(item);}for(const [key,n] of Object.entries(o.materials)){p.materials[key]-=n;q.materials[key]+=n;}}if(aa.bag.length>80||bb.bag.length>80||aa.gold>Number.MAX_SAFE_INTEGER||bb.gold>Number.MAX_SAFE_INTEGER||Object.values(aa.materials).some(n=>n>100000)||Object.values(bb.materials).some(n=>n>100000)){w.trades.delete(t.id);w.event(a,'가방 또는 보유 한도를 초과해 거래가 취소되었습니다.');w.event(b,'가방 또는 보유 한도를 초과해 거래가 취소되었습니다.');return;}a.exchangeBusy=b.exchangeBusy=true;clearMotion(a);clearMotion(b);t.settling=true;try{await w.onExchange(a,aa,b,bb);a.state=aa;b.state=bb;w.dirty(a);w.dirty(b);w.event(a,'거래 완료 · 양쪽 아이템과 골드가 함께 저장되었습니다.');w.event(b,'거래 완료 · 양쪽 아이템과 골드가 함께 저장되었습니다.');}catch{w.event(a,'저장 실패 · 거래를 취소하고 보유품을 유지했습니다.');w.event(b,'저장 실패 · 거래를 취소하고 보유품을 유지했습니다.');}finally{a.exchangeBusy=b.exchangeBusy=false;w.trades.delete(t.id);}}
export function mmoAction(w,p,data){const s=p.state,now=w.now(),kind=data.type;if(p.exchangeBusy)return true;
 if(kind==='travel'){
  if(socialId(w,p)){w.event(p,'거래·대련을 종료한 뒤 이동하세요.');return true;}
  const z=Object.hasOwn(ZONES,data.zone)?ZONES[data.zone]:null,portal=(TRAVEL_PORTALS[s.zone]||[]).find(x=>x.to===data.zone);
  if(!z||!portal){w.event(p,'현재 지역에서 바로 연결되지 않은 지역입니다.');return true;}
  if(s.level<z.level){w.event(p,'입장 레벨이 부족합니다. · Lv.'+z.level);return true;}
  clearMotion(p);s.zone=data.zone;s.x=768;s.y=portal.y>1500?790:1760;w.channel(p.channel,s.zone);w.dirty(p);w.event(p,ZONES[s.zone].name+' 입장');return true;
 }
 if(kind==='gather'){if(socialId(w,p))return true;const node=NODES.find(n=>n.id===data.node&&n.zone===s.zone);if(!node||distance(s,node)>110){w.event(p,'채집 지점 가까이 이동하세요.');return true;}if((s.gatherTimes[node.id]||0)>now){w.event(p,'이 자원은 아직 회복 중입니다.');return true;}s.gatherTimes[node.id]=now+node.cooldown;const amount=node.material==='crystal'?1:2+Math.floor(w.random()*2);s.materials[node.material]=Math.min(100000,s.materials[node.material]+amount);if(node.material==='crystal'&&w.random()<.15)s.materials.stardust=Math.min(100000,s.materials.stardust+1);progress(w,p,'gather');gainXp(s,20+Math.floor(s.level*2));clearMotion(p);w.dirty(p);w.event(p,MATERIALS[node.material]+' '+amount+'개 채집');return true;}
 if(kind==='craft'){if(socialId(w,p))return true;if(s.zone!=='surface'||distance(s,{x:1000,y:330})>145){w.event(p,'마을 상인 가까이에서 제작하세요.');return true;}const r=Object.hasOwn(RECIPES,data.recipe)?RECIPES[data.recipe]:null;if(!r||s.level<r.level||s.gold<r.gold||Object.entries(r.materials).some(([k,n])=>s.materials[k]<n)){w.event(p,'레벨·재료·골드를 확인하세요.');return true;}if(r.item&&s.bag.length>=80){w.event(p,'가방이 가득 찼습니다.');return true;}for(const [k,n] of Object.entries(r.materials))s.materials[k]-=n;s.gold-=r.gold;if(r.item)s.bag.push(r.item);if(r.potions)s.potions+=r.potions;w.dirty(p);w.event(p,r.name+' 제작 완료');return true;}
 if(kind==='dailyClaim'){if(s.zone!=='surface'||distance(s,{x:580,y:330})>145){w.event(p,'촌장 가까이에서 보상을 받으세요.');return true;}const d=daily(p,now),r=Object.hasOwn(DAILY_TASKS,data.task)?DAILY_TASKS[data.task]:null;if(!r||d.claimed.includes(data.task)||d[data.task]<r.goal)return true;d.claimed.push(data.task);s.gold+=r.gold;gainXp(s,r.xp+Math.floor(s.level*10));w.dirty(p);w.event(p,r.name+' 일일 보상 획득');return true;}
 if(kind==='tradeInvite'||kind==='duelInvite'){invite(w,p,data,kind==='duelInvite');return true;}
 if(kind==='tradeCancel'||kind==='duelCancel'){const t=(kind==='tradeCancel'?w.trades:w.duels).get(data.id);if(t?.players.includes(p.id)&&!t.settling)removeSocial(w,p);return true;}
 if(kind==='tradeAccept'){const t=w.trades.get(data.id);if(t&&t.from!==p.id&&t.players.includes(p.id)&&close(...t.players.map(id=>w.players.get(id)))){t.accepted=true;t.expires=now+180;}return true;}
 if(kind==='tradeOffer'){const t=w.trades.get(data.id);if(!t?.accepted||!t.players.includes(p.id)||t.settling)return true;const o={gold:Number(data.gold),items:data.items,materials:data.materials||{}};if(!validOffer(p,o)){w.event(p,'장착·귀속 아이템과 보유량을 확인하세요.');return true;}t.offers[p.id]=structuredClone(o);t.confirmed=[];t.expires=now+180;return true;}
 if(kind==='tradeConfirm'){const t=w.trades.get(data.id);if(!t?.accepted||!t.players.includes(p.id)||t.settling)return true;if(!t.confirmed.includes(p.id))t.confirmed.push(p.id);if(t.confirmed.length===2)return settle(w,t);return true;}
 if(kind==='duelAccept'){const t=w.duels.get(data.id);if(!t||t.from===p.id||!t.players.includes(p.id))return true;const ps=t.players.map(id=>w.players.get(id));if(!close(...ps)||ps.some(q=>q.state.y>590))return true;t.accepted=true;t.start=now+3;t.expires=now+123;t.health=Object.fromEntries(ps.map(q=>[q.id,1000]));t.next={};t.cooldowns={};for(const q of ps)clearMotion(q);return true;}
 if(kind==='duelAttack'){const t=[...w.duels.values()].find(t=>t.accepted&&t.players.includes(p.id));if(!t||now<t.start||now<(t.next[p.id]||0))return true;const other=w.players.get(t.players.find(id=>id!==p.id));if(!close(p,other))return true;const skill=Number(data.skill),j=w.jobs[s.job],ability=Number.isInteger(skill)&&skill>=0?j.skills[skill]:null;const cd=t.cooldowns[p.id]||Array(j.skills.length).fill(0),rankReq=Number(ability?.[5]?.rank)||0;if(skill>=0&&(!ability||s.level<ability[1]||s.rank<rankReq||!promotionSkillLearned(s,rankReq)||now<cd[skill]))return true;const mpCost=skillMpCost(s,ability);if(ability&&s.mp<mpCost){w.event(p,'마나가 부족합니다.');return true;}const range=Math.min(220,stats(s).range);if(distance(s,other.state)>range){w.event(p,'대련 상대에게 더 가까이 접근하세요.');return true;}t.next[p.id]=now+(ability?skillCastDelay(s,ability):basicAttackDelay(s));if(ability){s.mp=Math.max(0,s.mp-mpCost);w.dirty(p);cd[skill]=now+ability[2];t.cooldowns[p.id]=cd;}const mode=ability?.[4];if(mode==='heal'||mode==='partyHeal')t.health[p.id]=Math.min(1000,t.health[p.id]+(mode==='partyHeal'?240:160));else if(mode==='guard'||mode==='partyGuard'){t.guards??={};t.guards[p.id]=now+5;}else{const bonus=Math.min(.15,(s.rank*.03+Math.max(0,stats(s).atk-10-s.level*3-j.attack)/2500));const hit=Math.round(65*(ability?.[3]||1)*(1+bonus)*(t.guards?.[other.id]>now?.5:1));t.health[other.id]=Math.max(0,t.health[other.id]-hit);if(mode==='drain')t.health[p.id]=Math.min(1000,t.health[p.id]+Math.round(hit*.3));}p.attackSkill=Number.isInteger(skill)?skill:-1;p.attackTarget=other.id;const dx=other.state.x-s.x,dy=other.state.y-s.y,d=Math.hypot(dx,dy)||1;p.dirX=dx/d;p.dirY=dy/d;p.face=Math.abs(dx)>Math.abs(dy)?2:dy<0?1:0;p.flip=p.face===2&&dx<0;p.attackUntil=now+Math.min(.72,(ability?skillCastDelay(s,ability):basicAttackDelay(s))*.82);if(t.health[other.id]===0){s.pvpWins++;w.dirty(p);w.event(p,'PVP 대련 승리! 승수 +1 · 아이템 손실 없음');w.event(other,'대련 종료 · 성장과 장비는 유지됩니다.');w.duels.delete(t.id);}return true;}
 return false;
}
export function tickSystems(w){const now=w.now();for(const map of [w.trades,w.duels])for(const [id,t] of map){if(t.settling)continue;const [a,b]=t.players.map(id=>w.players.get(id));if(now>t.expires||!same(a,b)||(map===w.trades&&distance(a.state,b.state)>260)||(map===w.duels&&t.accepted&&(a.state.y>590||b.state.y>590||distance(a.state,b.state)>400))){map.delete(id);for(const p of [a,b])if(p)w.event(p,'거리·시간·접속 변화로 거래 또는 대련이 종료되었습니다.');}}
}
export function snapshotSystems(w,p){const t=[...w.trades.values()].find(t=>t.players.includes(p.id)),d=[...w.duels.values()].find(t=>t.players.includes(p.id));return {daily:structuredClone(daily(p,w.now())),nodes:NODES.filter(n=>n.zone===p.state.zone).map(n=>({...n,readyAt:p.state.gatherTimes[n.id]||0})),bosses:NAMED.map(b=>({...b,...bossWindow(b,w.now())})),trade:t?structuredClone(t):null,duel:d?structuredClone(d):null};}
