import {W,H,clamp,distance,walkable,pathfind,needXp} from './core.js';
import {JOBS,ITEMS,SLOTS,profile,stats,jobName,BUILD} from './catalog.js?v=20261006-online-2';
import {API_URL} from './config.js';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const apiBase=location.hostname==='junja-adventure-preview.onrender.com'?API_URL:'';
let token='',connectionKey='',legacy=null,roster=[],selectedSlot=0,state=profile(),view={x:768,y:355},connected=false,paused=false,serverNow=0,receivedAt=0,last=0,clock=0,lastSend=0,movePending=false,streamController=null,streamGeneration=0;
let path=[],selected=null,auto=false,cam={x:0,y:0},scale=1,face=0,flip=false,attackUntil=0,nearNpc=null,npcIntent=null,gesture=null,stick={x:0,y:0};
const keys=new Set(),enemies=new Map(),peers=new Map(),seenEvents=new Set(),npcs=[{id:'elder',x:580,y:330},{id:'merchant',x:1000,y:330}];
try{token=localStorage.getItem('junja-online-token')||'';const old=localStorage.getItem('junja-adventure-play-v2');if(old)legacy=JSON.parse(old);}catch{}
if(legacy)$('legacyRow').hidden=false;
const artReady=Promise.all(['hero','rogue','mage','healer','world','npcs','squirrel'].map(name=>new Promise((resolve,reject)=>{const im=new Image();im.onload=resolve;im.onerror=()=>reject(Error('캐릭터 이미지를 불러오지 못했어요. 다시 연결해 주세요.'));im.src='./assets/'+name+'.png';})));artReady.catch(()=>{});
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function now(){return serverNow+(performance.now()-receivedAt)/1000;}
async function api(route,data){const r=await fetch(apiBase+'/api/'+route,{method:data?'POST':'GET',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{}),...(connectionKey?{'x-adventure-connection':connectionKey}:{})},body:data?JSON.stringify(data):undefined});const json=await r.json();if(!r.ok)throw Error(json.error||'연결을 확인하세요.');return json;}
async function command(data){if(!connected)return;try{await api('action',data);}catch(e){toast(e.message);}}
function stopMovement(){keys.clear();stick={x:0,y:0};path=[];gesture=null;$('joystick').hidden=true;if(connected)command({type:'move',x:0,y:0,manual:true});}
function go(x,y){path=[];command({type:'navigate',x,y});$('marker').style.left=x+'px';$('marker').style.top=y+'px';$('marker').classList.remove('show');void $('marker').offsetWidth;$('marker').classList.add('show');}
function camera(force=false,dt=.016){const vw=$('viewport').clientWidth/scale,vh=$('viewport').clientHeight/scale;const x=clamp(view.x-vw*.5,Math.min(0,(W-vw)/2),Math.max(0,W-vw)),y=clamp(view.y-vh*.53,Math.min(0,(H-vh)/2),Math.max(0,H-vh)),f=force?1:1-Math.exp(-12*dt);cam.x+=(x-cam.x)*f;cam.y+=(y-cam.y)*f;$('world').style.transform=`scale(${scale}) translate3d(${-cam.x}px,${-cam.y}px,0)`;}
function resize(){scale=innerWidth<600?.85:Math.min(1,innerWidth/1150);camera(true);}
function screenToWorld(x,y){const r=$('viewport').getBoundingClientRect();return {x:(x-r.left)/scale+cam.x,y:(y-r.top)/scale+cam.y};}
function sprite(el,col,row,rows=3,mirror=false){el.style.backgroundPosition=`${col*100/3}% ${row*100/(rows-1)}%`;el.style.transform=mirror?'scaleX(-1)':'none';}
function actorArt(el,s){el.style.backgroundImage=`url('./assets/${JOBS[s.job].art}.png')`;}
function decorate(el,s){const eq=s.equipment||{};el.dataset.job=s.job;for(const slot of ['armor','head','weapon','cape','boots'])el.dataset[slot]=ITEMS[eq[slot]]?.tier||0;el.classList.toggle('promoted',!!s.rank);}
function layers(el){if(el.querySelector('.gear-layers'))return;const div=document.createElement('div');div.className='gear-layers';div.innerHTML='<i class="gear-cape"></i><i class="gear-armor"></i><i class="gear-head"></i><i class="gear-boots"></i><i class="gear-weapon"></i>';el.append(div);}
layers($('hero'));
function entity(type){const el=document.createElement('div');el.className='entity '+type;el.innerHTML='<div class="shadow"></div><div class="sprite"></div><b class="entity-name"></b><div class="life"><i></i></div><div class="tell" hidden></div>';return el;}
function updateSnapshot(data){if(data.disconnected){connected=false;streamController?.abort();toast(data.disconnected);showSelection();return;}if(!data.self)return;serverNow=data.now;receivedAt=performance.now();const old=state;state=data.self;auto=state.auto;connected=true;
 if(distance(view,state)>100){view={x:state.x,y:state.y};path=[];camera(true);}
 if(auto||state.navMoving){const me=data.players.find(p=>p.id===state.id);if(me){face=me.face;flip=me.flip;if(me.attacking)attackUntil=clock+.2;}}if(old.job!==state.job||old.rank!==state.rank||$('skillbar').childElementCount!==4)makeSkills();actorArt($('heroArt'),state);decorate($('hero'),state);$('hero').querySelector('.entity-name').textContent=state.name+' · '+jobName(state);document.querySelector('.portrait').style.backgroundImage=`url('./assets/${JOBS[state.job].art}.png')`;
 const mobIds=new Set();for(const e of data.enemies){mobIds.add(e.id);let entry=enemies.get(e.id);if(!entry){const el=entity('enemy'+(e.boss?' boss':''));el.querySelector('b').textContent=e.boss?'왕꼬리 다람쥐 · BOSS':'숲 다람쥐';el.addEventListener('pointerdown',ev=>{ev.stopPropagation();select(e.id);});$('enemyLayer').append(el);entry={el,art:el.querySelector('.sprite'),vx:e.x,vy:e.y};enemies.set(e.id,entry);}Object.assign(entry,e);entry.el.classList.toggle('dead',!e.alive);entry.el.querySelector('.life i').style.width=e.hp/e.max*100+'%';entry.el.querySelector('.tell').hidden=!e.tellAt;entry.el.classList.toggle('selected',selected===e.id);}
 for(const [id,e] of enemies)if(!mobIds.has(id)){e.el.remove();enemies.delete(id);}
 const peerIds=new Set();for(const p of data.players){if(p.id===state.id)continue;peerIds.add(p.id);let peer=peers.get(p.id);if(!peer){const el=entity('peer hero');layers(el);$('world').append(el);peer={el,art:el.querySelector('.sprite'),vx:p.x,vy:p.y};peers.set(p.id,peer);}Object.assign(peer,p);actorArt(peer.art,p);decorate(peer.el,p);peer.el.querySelector('b').textContent=p.name+' · '+jobName(p);peer.el.querySelector('.life i').style.width=p.hp/p.maxHp*100+'%';}
 for(const [id,p] of peers)if(!peerIds.has(id)){p.el.remove();peers.delete(id);}
 $('onlineCount').textContent=data.players.length+'명';$('saveStatus').textContent=data.saveStatus==='error'?'저장 재시도 중':data.saveStatus==='pending'?'서버 저장 대기':'계정에 저장됨';
 for(const event of data.events){if(seenEvents.has(event.id))continue;seenEvents.add(event.id);if(event.kind==='chat'){const row=document.createElement('p');row.textContent=event.text;$('chatLog').append(row);while($('chatLog').childElementCount>3)$('chatLog').firstChild.remove();}else{toast(event.text);$('toast').classList.toggle('rare-toast',event.kind==='rare');}}
 if(seenEvents.size>500)[...seenEvents].slice(0,300).forEach(id=>seenEvents.delete(id));hud();
}
async function consumeStream(generation){streamController?.abort();const controller=new AbortController();streamController=controller;
 try{const r=await fetch(apiBase+'/api/events',{headers:{authorization:'Bearer '+token,'x-adventure-connection':connectionKey},signal:controller.signal});if(!r.ok)throw Error('접속이 끊겼습니다.');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(generation===streamGeneration){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let index;while((index=buffer.indexOf('\n\n'))>=0){const event=buffer.slice(0,index);buffer=buffer.slice(index+2);if(event.startsWith('data: '))updateSnapshot(JSON.parse(event.slice(6)));}}
 }catch(e){if(controller.signal.aborted)return;}
 if(generation!==streamGeneration)return;connected=false;stopMovement();$('saveStatus').textContent='연결 끊김 · 재접속 필요';$('loading').hidden=false;$('authPanel').hidden=true;$('selectPanel').hidden=true;$('retryBtn').hidden=false;$('loadMessage').textContent='연결이 끊겼어요. 기록을 불러와 다시 접속하세요.';
}
async function showSelection(){streamGeneration++;streamController?.abort();connected=false;stopMovement();paused=false;$('modal').hidden=true;$('loading').hidden=false;$('authPanel').hidden=true;$('selectPanel').hidden=true;$('retryBtn').hidden=true;
 try{$('loadMessage').textContent='캐릭터를 준비하고 있어요…';const me=await api('me');await artReady;$('loadMessage').textContent='친구들과 함께하는 준자마을';roster=me.roster;$('welcome').textContent=me.name+' · 캐릭터 선택';$('characterCards').replaceChildren();for(const s of roster){const job=JOBS[s.job],b=document.createElement('button');b.type='button';b.className='character-card';b.dataset.slot=s.slot;b.setAttribute('aria-pressed',String(s.slot===selectedSlot));b.innerHTML=`<span class="character-preview"><img src="./assets/${job.art}.png" alt="${job.name}" decoding="sync"></span><b>${esc(s.rank?job.title:job.name)}</b><small>Lv.${s.level} · ${job.role}</small>`;b.onclick=()=>{selectedSlot=s.slot;document.querySelectorAll('.character-card').forEach(el=>el.setAttribute('aria-pressed',String(Number(el.dataset.slot)===selectedSlot)));};$('characterCards').append(b);}await Promise.all([...$('characterCards').querySelectorAll('img')].map(im=>im.decode()));$('selectPanel').hidden=false;
 }catch(e){token='';try{localStorage.removeItem('junja-online-token');}catch{}$('authPanel').hidden=false;$('selectPanel').hidden=true;$('authMessage').textContent=e.message;}
}
async function login(register=false){if(!$('authForm').reportValidity())return;const username=$('username').value.trim(),password=$('password').value;$('authMessage').textContent='접속 중…';$('loginBtn').disabled=$('registerBtn').disabled=true;
 try{const r=await api(register?'register':'login',{username,password,...(register&&legacy&&$('legacyCheck').checked?{legacy}:{})});token=r.token;try{localStorage.setItem('junja-online-token',token);}catch{}$('password').value='';await showSelection();}catch(e){$('authMessage').textContent=e.message;}finally{$('loginBtn').disabled=$('registerBtn').disabled=false;}
}
$('authForm').onsubmit=e=>{e.preventDefault();login();};$('registerBtn').onclick=()=>login(true);$('switchAccount').onclick=()=>{token='';try{localStorage.removeItem('junja-online-token');}catch{}$('authPanel').hidden=false;$('selectPanel').hidden=true;$('authMessage').textContent='';};
async function join(){$('joinBtn').disabled=true;$('loadMessage').textContent='준자마을에 접속 중…';try{await artReady;const r=await api('join',{slot:selectedSlot,channel:$('channelInput').value.trim()});connectionKey=r.connectionKey;state=r.snapshot.self;view={x:state.x,y:state.y};selected=null;path=[];updateSnapshot(r.snapshot);resize();makeSkills();face=0;flip=false;$('hero').style.left=view.x+'px';$('hero').style.top=view.y+'px';$('hero').style.zIndex=Math.round(view.y);sprite($('heroArt'),0,0);$('loading').hidden=true;last=performance.now();consumeStream(++streamGeneration);toast(state.channel+'에 접속했습니다. 친구에게 같은 채널을 알려 주세요.');}catch(e){$('loadMessage').textContent=e.message;}finally{$('joinBtn').disabled=false;}}
$('joinBtn').onclick=join;$('retryBtn').onclick=showSelection;
function select(id){const e=enemies.get(id);if(!e?.alive)return;selected=id;npcIntent=null;path=[];if(distance(view,e)>stats(state).range*.8)go(e.x,e.y);hud();}
function attack(skill=-1){if(paused||!connected)return;const ability=JOBS[state.job].skills[skill];if(ability&&['heal','partyHeal','guard','partyGuard'].includes(ability[4])){command({type:'attack',skill});effect(ability[4].toLowerCase().includes('heal')?'heal':'guard');return;}let e=enemies.get(selected);if(!e?.alive)e=[...enemies.values()].filter(e=>e.alive&&distance(view,e)<stats(state).range).sort((a,b)=>distance(a,view)-distance(b,view))[0];if(!e){toast('다람쥐를 선택해 주세요.');return;}selected=e.id;if(distance(state,e)>stats(state).range){go(e.x,e.y);toast('공격 범위까지 이동합니다.');return;}command({type:'attack',skill,target:e.id});attackUntil=clock+.34;face=Math.abs(e.x-view.x)>Math.abs(e.y-view.y)?2:e.y<view.y?1:0;flip=face===2&&e.x<view.x;path=[];if(skill>=0)effect(state.job);hud();}
function effect(kind){const el=document.createElement('div');el.className='skill-effect '+kind;el.style.left=view.x+'px';el.style.top=view.y+'px';$('effects').append(el);setTimeout(()=>el.remove(),650);}
function makeSkills(){$('skillbar').replaceChildren();JOBS[state.job].skills.forEach((s,i)=>{const b=document.createElement('button');b.id='skill'+i;b.innerHTML=`<b>${s[0]}</b><small>Lv.${s[1]}</small>`;b.onclick=()=>attack(i);$('skillbar').append(b);});}
function hud(){const st=stats(state),t=now();$('playerName').textContent=state.name||'준자';$('level').textContent='Lv.'+state.level+' '+jobName(state);$('hpText').textContent=Math.ceil(state.hp)+' / '+st.hp;$('hpBar').style.width=state.hp/st.hp*100+'%';$('expBar').style.width=Math.min(100,state.exp/needXp(state.level)*100)+'%';$('expText').textContent='EXP '+state.exp+' / '+needXp(state.level);$('gold').textContent=state.gold.toLocaleString()+' G';$('zone').textContent=(view.y>590?'다람쥐 숲':'준자마을')+' · '+(state.channel||'');$('potionLabel').textContent=state.potions+'개';$('potionBtn').disabled=!connected||state.potions<=0;
 const quests={available:['작은 다람쥐의 위협','촌장에게 첫 임무를 받아 주세요.','촌장 찾아가기'],active:['작은 다람쥐의 위협',`공동 처치 ${Math.min(10,state.questKills)} / 10 · 200 G, 물약 3개`,'숲으로 이동'],ready:['임무 완료','촌장에게 보상을 받아 주세요.','촌장에게 보고'],complete:['왕꼬리의 흔적','보스 임무를 수락해 주세요.','촌장 찾아가기'],bossActive:['숲의 수호자 왕꼬리','함께 왕꼬리 처치 · 희귀 장비 10%','보스 찾아가기'],bossReady:['보스 임무 완료','빛나는 무기 보상을 받아 주세요.','촌장에게 보고'],done:['준자마을의 수호자','Lv.10 + 왕꼬리 1회 → 승급 · 희귀 장비 도전','숲으로 이동']};const q=quests[state.quest];$('questTitle').textContent=q[0];$('questText').textContent=q[1];$('questAction').textContent=q[2];const e=enemies.get(selected);$('targetPanel').hidden=!e?.alive;if(e?.alive){$('targetName').textContent=e.boss?'왕꼬리 다람쥐':'숲 다람쥐';$('targetRange').textContent=Math.round(distance(view,e)/24)+'m';$('targetHp').style.width=e.hp/e.max*100+'%';}
 $('attackBtn').disabled=paused||!connected||t<(state.nextAttack||0);$('attackLabel').textContent=e?.alive?distance(state,e)>st.range?'접근 후 공격':'공격 가능':'대상 선택';$('autoBtn').setAttribute('aria-pressed',String(auto));$('autoBtn').querySelector('small').textContent=auto?'ON':'OFF';$('contextBtn').hidden=!nearNpc;JOBS[state.job].skills.forEach((s,i)=>{const b=$('skill'+i);if(!b)return;const locked=state.level<s[1]||(i===3&&!state.rank),cd=Math.max(0,(state.cooldowns?.[i]||0)-t);b.disabled=paused||!connected||locked||cd>0;b.querySelector('small').textContent=locked?(i===3?'승급 필요':'Lv.'+s[1]):cd>0?Math.ceil(cd)+'초':'준비';});
}
function modal(title,body,actions=[]){paused=true;stopMovement();$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modalActions').replaceChildren();for(const [label,fn] of actions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{closeModal();fn();};$('modalActions').append(b);}$('modal').hidden=false;$('modalClose').focus();}
function closeModal(){paused=false;$('modal').hidden=true;$('viewport').focus({preventScroll:true});}
function seekNpc(id){selected=null;command({type:'auto',on:false});const n=npcs.find(n=>n.id===id);go(n.x,n.y+60);npcIntent=id;}
function talk(id){if(id==='merchant'){modal('약초 · 장비 상인','<p>물약은 체력의 50%를 회복합니다. 장비는 가방에서 장착하세요.</p><p>보유 '+state.gold.toLocaleString()+' G</p>',[['물약 · 30 G',()=>command({type:'buy',item:'potion'})],['치료 · 20 G',()=>command({type:'buy',item:'heal'})],...['leather','hood','boots','cape'].map(item=>[ITEMS[item].name+' · '+({leather:120,hood:100,boots:80,cape:180})[item]+' G',()=>command({type:'buy',item})])]);return;}const lines={available:'다람쥐 10마리를 물리쳐 주겠니? 친구와 함께 공격해도 처치가 인정된단다.',active:'다람쥐 '+state.questKills+' / 10. 친구와 힘을 합쳐 보렴.',ready:'고맙다! 200 G, 경험치 80과 물약 3개를 받아라.',complete:'왕꼬리를 물리쳐라. 참여자마다 희귀 장비를 얻을 기회가 있단다.',bossActive:'왕꼬리에 25 이상의 피해를 주거나 회복으로 지원하면 보상을 받을 수 있단다.',bossReady:'빛나는 무기, 500 G, 경험치 180을 받아라.',done:'10레벨과 왕꼬리 1회 처치를 달성하면 승급할 수 있단다.'};const actions=[];if(['available','complete','ready','bossReady'].includes(state.quest))actions.push([['ready','bossReady'].includes(state.quest)?'보상 받기':state.quest==='available'?'임무 수락':'보스 임무 수락',()=>command({type:'quest'})]);actions.push(['승급·직업 보기',jobWindow]);modal('준자마을 촌장','<p>'+lines[state.quest]+'</p>',actions);}
function jobWindow(){const job=JOBS[state.job],desc={hit:'강력한 단일 공격',area:'대상 주변 광역 공격',drain:'공격과 함께 체력 회복',slow:'광역 피해 · 5초 둔화',heal:'가까운 아군 체력 35% 회복',partyHeal:'가까운 아군 체력 60% 회복',guard:'7초 동안 받는 피해 60% 감소',partyGuard:'가까운 아군에게 7초 보호'};const actions=[['촌장 찾아가기',()=>seekNpc('elder')]];if(!state.rank)actions.push([job.title+' 승급',()=>command({type:'promote'})]);for(const [id,j] of Object.entries(JOBS))if(id!==state.job)actions.push([j.name+'로 변경 · 500 G',()=>command({type:'job',job:id})]);modal('직업 · 승급',`<p>현재 <strong>${jobName(state)}</strong> · Lv.${state.level}</p><p>승급: 10레벨 + 왕꼬리 1회 (${state.bossKills}회). 촌장 가까이에서 승급하면 네 번째 스킬이 열립니다.</p><p>직업 변경: 10레벨 + 500 G. 성장·장비를 유지합니다.</p>${job.skills.map((s,i)=>`<p><b>${s[0]}</b> · ${i===3?'승급 후':'Lv.'+s[1]} · ${s[2]}초<br>${desc[s[4]]}</p>`).join('')}`,actions);}
function bagWindow(){const st=stats(state),itemText=id=>ITEMS[id]?esc(ITEMS[id].name):'미장착',slots=Object.entries(SLOTS).map(([slot,name])=>`<button class="equip-slot slot-${slot}" data-unequip="${slot}"><small>${name}</small><b class="${ITEMS[state.equipment[slot]]?.rarity||''}">${itemText(state.equipment[slot])}</b></button>`).join('');modal('장비 · 가방',`<div class="paperdoll"><div id="dollActor" class="doll-actor entity hero"><div class="sprite" style="background-image:url('./assets/${JOBS[state.job].art}.png')"></div></div>${slots}</div><div class="combat-stats"><span>공격 <b>${st.atk}</b></span><span>방어 <b>${st.def}</b></span><span>체력 <b>${st.hp}</b></span></div><p>무기·투구·갑옷·망토·신발은 외형에 반영됩니다.</p><div class="bag-items">${[...new Set(state.bag)].map(id=>{const item=ITEMS[id],eq=state.equipment[item.slot]===id;return `<button data-equip="${id}" class="item-card ${item.rarity}"><b>${itemText(id)}</b><small>${SLOTS[item.slot]} · ${item.atk?'공격 +'+item.atk+' ':''}${item.def?'방어 +'+item.def+' ':''}${item.hp?'체력 +'+item.hp:''}</small><span>${eq?'장착 중':'장착'} · ${state.bag.filter(i=>i===id).length}개</span></button>`;}).join('')}</div><p>물약 ${state.potions}개 · 꼬리털 ${state.tails}개 · ${state.gold.toLocaleString()} G</p><p>왕꼬리: 희귀 장비 10% · 일반 장비 30% · 장비 없음 60%. 희귀 6종은 동일 확률이며 개인별 독립 추첨합니다.</p>`,[['물약 사용',()=>command({type:'potion'})]]);layers($('dollActor'));decorate($('dollActor'),state);document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=async()=>{await command({type:'equip',item:b.dataset.equip});setTimeout(bagWindow,180);});document.querySelectorAll('[data-unequip]').forEach(b=>b.onclick=()=>{if(b.dataset.unequip==='weapon'){toast('다른 무기로 교체하세요.');return;}command({type:'unequip',slot:b.dataset.unequip});closeModal();});}
function onlineWindow(){modal('함께 모험하기',`<p>현재 채널 <b>${esc(state.channel)}</b> · ${peers.size+1}명</p><p>친구에게 주소와 채널 이름을 알려 주세요. 같은 채널에서 이동·몬스터·보스 체력을 공유합니다.</p><p>접속: ${[state.name,...[...peers.values()].map(p=>p.name)].map(esc).join(', ')}</p><p>채널마다 최대 24명. 캐릭터 4종은 각각 기록이 저장됩니다.</p>`,[['초대 링크 복사',async()=>{const url=new URL(location.href);url.searchParams.set('channel',state.channel);try{await navigator.clipboard.writeText(url.href);toast('초대 링크를 복사했습니다.');}catch{modal('초대 링크','<p>'+esc(url.href)+'</p>');}}],['캐릭터·채널 변경',showSelection],['로그아웃',async()=>{await api('logout',{}).catch(()=>{});streamGeneration++;streamController?.abort();connected=false;token='';try{localStorage.removeItem('junja-online-token');}catch{}$('loading').hidden=false;$('selectPanel').hidden=true;$('authPanel').hidden=false;stopMovement();}]]);}
function chatWindow(){modal('채널 채팅','<form id="chatForm"><label>메시지<input id="chatInput" maxlength="100" placeholder="친구에게 한마디" autocomplete="off"></label><button type="submit">보내기</button></form>');$('chatForm').onsubmit=e=>{e.preventDefault();const text=$('chatInput').value;closeModal();command({type:'chat',text});};$('chatInput').focus();}
$('viewport').addEventListener('pointerdown',ev=>{if(paused||!connected||ev.target.closest('button,.enemy'))return;selected=null;command({type:'auto',on:false});npcIntent=null;const p=screenToWorld(ev.clientX,ev.clientY);go(p.x,p.y);gesture={id:ev.pointerId,x:ev.clientX,y:ev.clientY,drag:false};$('viewport').setPointerCapture(ev.pointerId);});
$('viewport').addEventListener('pointermove',ev=>{if(!gesture||ev.pointerId!==gesture.id)return;const dx=ev.clientX-gesture.x,dy=ev.clientY-gesture.y;if(Math.hypot(dx,dy)>9)gesture.drag=true;if(gesture.drag){path=[];stick={x:dx,y:dy};$('joystick').hidden=false;$('joystick').style.left=gesture.x+'px';$('joystick').style.top=gesture.y+'px';const d=Math.hypot(dx,dy),r=Math.min(27,d);$('joystick').querySelector('i').style.transform=d?`translate(${dx/d*r}px,${dy/d*r}px)`:'none';}});
function release(){gesture=null;stick={x:0,y:0};$('joystick').hidden=true;}for(const event of ['pointerup','pointercancel','lostpointercapture'])$('viewport').addEventListener(event,release);
window.addEventListener('keydown',ev=>{if(ev.target.closest('input,textarea'))return;if(paused){if(ev.key==='Escape')closeModal();return;}const key=ev.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','w','a','s','d'].includes(key)){ev.preventDefault();keys.add(key);path=[];npcIntent=null;if(auto)command({type:'auto',on:false});if(key===' ')attack();}if(['1','2','3','4'].includes(key))attack(Number(key)-1);if(key==='e'&&nearNpc)talk(nearNpc.id);if(key==='q')attack(0);});window.addEventListener('keyup',ev=>keys.delete(ev.key.toLowerCase()));window.addEventListener('blur',stopMovement);document.addEventListener('visibilitychange',()=>{stopMovement();last=performance.now();});window.addEventListener('resize',resize);
for(const n of npcs)$(n.id).onclick=()=>distance(view,n)<115?talk(n.id):seekNpc(n.id);$('contextBtn').onclick=()=>nearNpc&&talk(nearNpc.id);$('attackBtn').onclick=()=>attack();$('potionBtn').onclick=()=>command({type:'potion'});$('autoBtn').onclick=()=>{path=[];npcIntent=null;command({type:'auto',on:!auto});toast(!auto?'자동 사냥 ON · 숲에서 작동':'자동 사냥 OFF');};$('homeBtn').onclick=()=>{stopMovement();selected=null;command({type:'home'});};$('questToggle').onclick=()=>{$('quest').classList.toggle('collapsed');$('questToggle').textContent=$('quest').classList.contains('collapsed')?'+':'−';};$('questAction').onclick=()=>{if(['available','ready','complete','bossReady'].includes(state.quest))seekNpc('elder');else if(state.quest==='bossActive'){const e=[...enemies.values()].find(e=>e.boss);if(e?.alive)select(e.id);else toast('재출현까지 '+Math.max(0,Math.ceil((e?.respawn||0)-now()))+'초');}else go(768,720);};$('bagBtn').onclick=bagWindow;$('jobBtn').onclick=jobWindow;$('onlineBtn').onclick=onlineWindow;$('chatBtn').onclick=chatWindow;$('helpBtn').onclick=()=>modal('모험 안내','<p>빈 곳 터치로 이동. 화면 어디서든 드래그하면 방향 이동합니다. PC: WASD / 방향키, Space 공격, Q 첫 스킬, 1~4 스킬, E 대화.</p><p>촌장 임무 → 다람쥐 10마리 → 왕꼬리 → Lv.10 승급. 직업에 따라 공격 범위·스킬이 달라집니다.</p><p>가방에서 장비를 장착하세요. 보스 보상은 공격하거나 도사 회복으로 지원한 참여자에게 따로 지급됩니다.</p><p>성장은 계정에 저장됩니다. 같은 아이디의 동시 접속은 마지막 접속만 유지됩니다.</p>');$('modalClose').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal();};
let hudAt=0;
function frame(time){const dt=Math.min(.05,(time-last)/1000||.016);last=time;clock+=dt;if(connected){let dx=0,dy=0;if(!paused&&!document.hidden){dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(!dx&&!dy&&Math.hypot(stick.x,stick.y)>5){dx=stick.x;dy=stick.y;}if(!dx&&!dy&&path.length){if(distance(view,path[0])<16)path.shift();if(path.length){dx=path[0].x-view.x;dy=path[0].y-view.y;}}}const len=Math.hypot(dx,dy);if(len){dx/=len;dy/=len;}if(!auto&&clock>=attackUntil&&len){const x=view.x+dx*250*dt,y=view.y+dy*250*dt;if(walkable(x,view.y))view.x=x;if(walkable(view.x,y))view.y=y;face=Math.abs(dx)>Math.abs(dy)?2:dy<0?1:0;flip=face===2&&dx<0;}if(!len||auto){const f=1-Math.exp(-18*dt);view.x+=(state.x-view.x)*f;view.y+=(state.y-view.y)*f;}else if(distance(view,state)>40){view.x+=(state.x-view.x)*Math.min(1,dt*5);view.y+=(state.y-view.y)*Math.min(1,dt*5);}
 if(clock-lastSend>=.12&&!movePending){lastSend=clock;movePending=true;api('action',{type:'move',x:dx,y:dy,manual:len>0}).catch(()=>{}).finally(()=>movePending=false);}sprite($('heroArt'),clock<attackUntil?3:len||auto||state.navMoving?1+Math.floor(clock*9)%2:0,face,3,flip);$('hero').style.left=view.x+'px';$('hero').style.top=view.y+'px';$('hero').style.zIndex=Math.round(view.y);$('hero').classList.toggle('attacking',clock<attackUntil);$('hero').classList.toggle('guarded',(state.guard||0)>now());
 for(const e of enemies.values()){const f=1-Math.exp(-15*dt);e.vx+=(e.x-e.vx)*f;e.vy+=(e.y-e.vy)*f;e.el.style.left=e.vx+'px';e.el.style.top=e.vy+'px';e.el.style.zIndex=Math.round(e.vy);sprite(e.art,e.tellAt?3:1+Math.floor(clock*7)%2,e.boss?1:0,2);}for(const p of peers.values()){const f=1-Math.exp(-16*dt);p.vx+=(p.x-p.vx)*f;p.vy+=(p.y-p.vy)*f;p.el.style.left=p.vx+'px';p.el.style.top=p.vy+'px';p.el.style.zIndex=Math.round(p.vy);sprite(p.art,p.attacking?3:p.moving?1+Math.floor(clock*9)%2:0,p.face,3,p.flip);}nearNpc=npcs.find(n=>distance(view,n)<115)||null;if(npcIntent&&nearNpc?.id===npcIntent&&!path.length){const id=npcIntent;npcIntent=null;talk(id);}camera(false,dt);if(clock-hudAt>.1){hud();hudAt=clock;}}
 requestAnimationFrame(frame);}
const invite=new URL(location.href).searchParams.get('channel');if(invite&&/^[A-Za-z0-9가-힣_-]{2,16}$/.test(invite))$('channelInput').value=invite;if(innerWidth<600){$('quest').classList.add('collapsed');$('questToggle').textContent='+';}resize();makeSkills();requestAnimationFrame(frame);if(token)showSelection();
window.__adventure={build:BUILD,snapshot:()=>({...state,connected,paused,auto,selected,peers:[...peers.values()].map(({id,name,x,y,job,equipment})=>({id,name,x,y,job,equipment})),enemies:[...enemies.values()].map(({id,x,y,hp,alive,boss})=>({id,x,y,hp,alive,boss}))})};
