import {normalize} from './core.js';
import {EXTRA_ITEMS,LEVEL_CAP,MMO_XP,MMO_HP} from './mmo-data.js';
export {MMO_XP as needXp} from './mmo-data.js';
export const BUILD='20261009-ascension56';
export const JOBS={
 warrior:{name:'전사',title:'검호',rankTitles:['전사','검투사','대검기사','붉은성기사','천룡검황','창세검성','천상무신'],role:'근접 · 방어',art:'hero',color:'#efbd68',attack:3,def:4,range:115,mana:70,speed:1,attackDelay:.56,skills:[['회전베기',2,4,1.9,'area',{mp:8,mpPct:.10,cast:.55,center:'self',radius:175,knockback:38}],['철벽',4,8,0,'guard',{mp:12,mpPct:.12,cast:.35,guard:8,guardFactor:.28}],['강타',8,7,3.4,'hit',{mp:14,mpPct:.15,cast:.8,stun:1.1,knockback:55}],['검기폭풍',10,14,2.8,'area',{mp:20,mpPct:.22,cast:1.15,center:'target',radius:245,hits:3,knockback:24,rank:1}],['파천격',200,18,5.0,'hit',{mp:28,mpPct:.27,cast:1.0,stun:1.4,bossStun:.4,knockback:85,rank:2}],['용혈폭진',300,21,4.8,'area',{mp:34,mpPct:.31,cast:1.35,center:'self',radius:310,stun:.8,bossStun:.25,knockback:45,rank:3}],['천룡참',400,24,6.5,'area',{mp:38,mpPct:.35,cast:1.7,center:'target',radius:330,stun:1.2,bossStun:.5,knockback:70,rank:4}],['균열파천',500,26,8.1,'area',{mp:48,mpPct:.37,cast:1.4,center:'target',radius:360,stun:1.2,bossStun:.48,rank:5}],['영겁심판',650,30,10.8,'area',{mp:62,mpPct:.44,cast:1.85,center:'target',radius:410,stun:1.5,bossStun:.65,rank:6}]]},
 rogue:{name:'도적',title:'그림자',rankTitles:['도적','암살자','어둠추적자','월식군주','심연제왕','절대그림자','무영신왕'],role:'기습 · 연속공격',art:'rogue',color:'#e791a4',attack:5,def:1,range:120,mana:80,speed:1.12,attackDelay:.50,skills:[['쌍검난무',2,3,2.45,'hit',{mp:7,mpPct:.09,cast:.45,hits:4}],['흡혈검',4,7,1.8,'drain',{mp:11,mpPct:.13,cast:.55,leech:.6}],['그림자 일격',8,9,3.7,'hit',{mp:14,mpPct:.17,cast:.7,execute:.35,executeBonus:1.45,stun:.55}],['월영참',10,14,3.1,'area',{mp:19,mpPct:.22,cast:.95,center:'target',radius:190,slow:2.5,rank:1}],['암영연쇄',200,16,4.6,'hit',{mp:26,mpPct:.26,cast:.72,hits:5,execute:.30,executeBonus:1.35,rank:2}],['월식분신',300,18,5.4,'area',{mp:32,mpPct:.30,cast:.88,center:'target',radius:245,slow:3.5,leech:.28,rank:3}],['월식멸살',400,20,7.0,'hit',{mp:36,mpPct:.34,cast:1.35,execute:.45,executeBonus:1.8,stun:1.0,bossStun:.35,leech:.35,rank:4}],['균열그림자',500,23,8.2,'hit',{mp:44,mpPct:.36,cast:1.05,hits:5,execute:.45,executeBonus:1.75,rank:5}],['무영참',650,28,11.1,'area',{mp:58,mpPct:.43,cast:1.45,center:'target',radius:300,leech:.35,stun:1.2,rank:6}]]},
 mage:{name:'주술사',title:'현자',rankTitles:['주술사','화염술사','천뢰술사','성운대현자','천명법황','성계대마신','운명창조자'],role:'원거리 · 광역',art:'mage',color:'#b6a1fb',attack:4,def:0,range:330,mana:120,speed:.94,attackDelay:.62,skills:[['화염구',2,3,2.2,'hit',{mp:9,mpPct:.10,cast:.65,splash:90,splashFactor:.45}],['서리장',4,6,1.45,'slow',{mp:13,mpPct:.13,cast:.85,center:'target',radius:205,slow:5}],['뇌전폭풍',8,10,2.7,'area',{mp:18,mpPct:.18,cast:1.1,chain:4,chainRadius:250,falloff:.82,stun:.35}],['천둥심판',10,16,3.5,'area',{mp:26,mpPct:.24,cast:1.45,center:'target',radius:270,stun:1.15,bossStun:.35,rank:1}],['천뢰사슬',200,18,4.4,'area',{mp:31,mpPct:.28,cast:1.25,chain:6,chainRadius:320,falloff:.88,stun:.45,rank:2}],['성운폭발',300,22,5.8,'area',{mp:40,mpPct:.34,cast:1.55,center:'target',radius:340,slow:4,stun:.8,bossStun:.3,rank:3}],['천명멸계',400,26,7.5,'area',{mp:48,mpPct:.40,cast:1.9,center:'target',radius:380,stun:1.5,bossStun:.6,rank:4}],['성운균열',500,29,9.1,'area',{mp:58,mpPct:.44,cast:1.75,center:'target',radius:400,chain:6,rank:5}],['영겁멸계',650,33,12.0,'area',{mp:72,mpPct:.49,cast:2.1,center:'target',radius:445,stun:1.6,bossStun:.65,rank:6}]]},
 healer:{name:'도사',title:'선인',rankTitles:['도사','치유선사','수호도인','연화성인','천광선제','천명의 구원자','영겁성신'],role:'회복 · 지원',art:'healer',color:'#9de1af',attack:1,def:2,range:290,mana:130,speed:.92,attackDelay:.64,skills:[['성광탄',2,3,2.05,'hit',{mp:8,mpPct:.09,cast:.6,selfHeal:.1}],['생명의 숨결',4,8,0,'heal',{mp:14,mpPct:.15,cast:.8,heal:.38,radius:310}],['수호결계',8,10,0,'partyGuard',{mp:18,mpPct:.17,cast:.7,guard:7,guardFactor:.5,radius:330}],['연화회복',10,16,0,'partyHeal',{mp:28,mpPct:.25,cast:1.25,heal:.62,radius:360,guard:2,guardFactor:.65,rank:1}],['성역결계',200,18,0,'partyGuard',{mp:32,mpPct:.28,cast:1.0,guard:10,guardFactor:.38,radius:400,rank:2}],['연화성역',300,22,0,'partyHeal',{mp:42,mpPct:.35,cast:1.45,heal:.78,radius:430,guard:4,guardFactor:.50,rank:3}],['천광강림',400,28,0,'partyHeal',{mp:55,mpPct:.42,cast:1.8,heal:.92,radius:470,guard:6,guardFactor:.42,rank:4}],['생명의 기원',500,24,0,'partyHeal',{mp:62,mpPct:.46,cast:1.5,heal:1.0,radius:510,guard:7,guardFactor:.36,rank:5}],['영겁의 가호',650,28,0,'partyGuard',{mp:78,mpPct:.52,cast:1.4,guard:13,guardFactor:.27,radius:560,rank:6}]]},
};
export const SLOTS={head:'투구',weapon:'무기',armor:'갑옷',cape:'망토',boots:'신발',ring:'반지',ear:'귀걸이'};
export const ITEMS={
 ...EXTRA_ITEMS,
 training:{name:'수련 무기',slot:'weapon',rarity:'normal',atk:0,tier:0},
 glowing:{name:'빛나는 무기',slot:'weapon',rarity:'uncommon',atk:8,speed:.02,tier:1,shop:true,price:12000},
 leather:{name:'숲지기 갑옷',slot:'armor',rarity:'normal',def:3,hp:15,tier:1,shop:true,price:3500},
 hood:{name:'숲지기 투구',slot:'head',rarity:'normal',def:2,tier:1,shop:true,price:2000},
 boots:{name:'숲지기 장화',slot:'boots',rarity:'normal',def:1,hp:8,speed:.025,tier:1,shop:true,price:1800},
 cape:{name:'초록 망토',slot:'cape',rarity:'uncommon',def:2,hp:18,tier:1,shop:true,price:6000},
 kingblade:{name:'왕꼬리의 서광',slot:'weapon',rarity:'rare',atk:18,speed:.04,tier:2,shop:true,price:55000},
 kingarmor:{name:'왕꼬리 비늘갑옷',slot:'armor',rarity:'rare',def:8,hp:40,tier:2,shop:true,price:48000},
 kingcrown:{name:'왕꼬리 왕관',slot:'head',rarity:'rare',def:4,hp:20,tier:2,shop:true,price:35000},
 kingcape:{name:'달빛 망토',slot:'cape',rarity:'rare',atk:4,hp:30,tier:2,shop:true,price:42000},
 kingring:{name:'숲의 반지',slot:'ring',rarity:'rare',atk:3,hp:15,speed:.045,tier:2,shop:true,price:32000},
 kingear:{name:'이슬 귀걸이',slot:'ear',rarity:'rare',def:2,hp:20,tier:2,shop:true,price:30000},
};
export const RARE_POOL=['kingblade','kingarmor','kingcrown','kingcape','kingring','kingear'];
export const CRYSTAL_POOL=['crystalblade','crystalarmor','crystalcrown','crystalcape','crystalboots','crystalring','crystalear'];
export const RUIN_POOL=['ruinblade','ruinarmor','ruincrown','ruincape','ruinboots','ruinring','ruinear'];
export const UNCOMMON_POOL=['leather','hood','boots','cape','ironblade','ironarmor'];
export const LEGENDARY_POOL=['astralblade','astralarmor','astralcape','astralcrown','astralboots','astralring','astralear','shadowblade','shadowarmor','shadowcape','shadowcrown','shadowboots','shadowring','shadowear','dragonblade','dragonarmor','dragoncape','dragoncrown','dragonboots','dragonring','dragonear'];
export const MYTHIC_POOL=['mythicblade','mythicarmor','mythiccape','mythiccrown','mythicboots','mythicring','mythicear','voidblade','voidarmor','voidcape','voidcrown','voidboots','voidring','voidear','primeblade','primearmor','primecape','primecrown','primeboots','primering','primeear'];
export const RAID_POOL=['raidblade','raidarmor','raidcape','raidcrown','raidboots','raidring','raidear'];
export const RIFT_POOL=['riftblade','riftarmor','riftcape','riftcrown','riftboots','riftring','riftear'];
export const ECLIPSE_POOL=['eclipseblade','eclipsearmor','eclipsecape','eclipsecrown','eclipseboots','eclipsering','eclipseear'];
export const ETERNAL_POOL=['eternalblade','eternalarmor','eternalcape','eternalcrown','eternalboots','eternalring','eternalear'];
export const MAX_ENHANCE=15;
export function enhanceChance(level){return [1,1,1,.95,.90,.82,.70,.58,.45,.32,.22,.14,.08,.04,.02][Math.max(0,Math.min(MAX_ENHANCE-1,Math.floor(level)||0))]??0;}
export function enhancementLevel(s,id){return Math.max(0,Math.min(MAX_ENHANCE,Math.floor(Number(s.enhancements?.[id])||0)));}
export function itemSellPrice(item){if(!item)return 0;if(item.price)return Math.max(1,Math.floor(item.price*.30));const perLevel={normal:100,uncommon:320,rare:1200,legendary:6000,mythic:15000}[item.rarity]||120;return Math.max(1,Math.floor(((item.level||1)*perLevel+(item.tier||0)*5000)*.35));}
export function enhanceMultiplier(level){const n=Math.max(0,Math.min(MAX_ENHANCE,Math.floor(Number(level)||0)));return 1+Math.min(n,5)*.07+Math.min(Math.max(n-5,0),5)*.09+Math.min(Math.max(n-10,0),3)*.12+Math.min(Math.max(n-13,0),2)*.18;}
export function enhanceGrade(level){const n=Math.max(0,Math.min(MAX_ENHANCE,Math.floor(Number(level)||0)));return n>=15?'신화강화':n>=12?'초월':n>=9?'명장':n>=6?'정예':n>=3?'단련':'기본';}
export const MYTHIC_SETS={
 mythic:{name:'천제 세트',prefix:'mythic',bonuses:[{count:3,atk:.06,hp:.08,text:'3세트 · 공격 +6% / HP +8%'},{count:5,def:.10,mp:.08,text:'5세트 · 방어 +10% / MP +8%'},{count:7,atk:.08,hp:.10,speed:.025,text:'7세트 · 공격 +8% / HP +10% / 속도 +2.5%'}]},
 void:{name:'공허제 세트',prefix:'void',bonuses:[{count:3,atk:.08,hp:.10,text:'3세트 · 공격 +8% / HP +10%'},{count:5,def:.12,speed:.035,text:'5세트 · 방어 +12% / 속도 +3.5%'},{count:7,atk:.12,hp:.15,text:'7세트 · 공격 +12% / HP +15%'}]},
 prime:{name:'태초신 세트',prefix:'prime',bonuses:[{count:3,atk:.10,def:.08,text:'3세트 · 공격 +10% / 방어 +8%'},{count:5,hp:.18,mp:.12,text:'5세트 · HP +18% / MP +12%'},{count:7,atk:.15,def:.12,speed:.05,text:'7세트 · 공격 +15% / 방어 +12% / 속도 +5%'}]},
 raid:{name:'신격 세트',prefix:'raid',bonuses:[{count:3,atk:.12,def:.12,hp:.12,text:'3세트 · 공격/방어/HP +12%'},{count:5,atk:.15,def:.15,hp:.20,text:'5세트 · 공격/방어 +15% / HP +20%'},{count:7,atk:.20,def:.18,hp:.25,speed:.07,text:'7세트 · 공격 +20% / 방어 +18% / HP +25% / 속도 +7%'}]},
 rift:{name:'균열의 파수꾼',prefix:'rift',bonuses:[{count:3,atk:.11,hp:.14,text:'3세트 · 공격 +11% / HP +14%'},{count:5,def:.14,mp:.13,text:'5세트 · 방어 +14% / MP +13%'},{count:7,atk:.13,hp:.16,speed:.04,text:'7세트 · 공격 +13% / HP +16% / 속도 +4%'}]},
 eclipse:{name:'월식의 지배자',prefix:'eclipse',bonuses:[{count:3,atk:.15,def:.12,text:'3세트 · 공격 +15% / 방어 +12%'},{count:5,hp:.20,speed:.04,text:'5세트 · HP +20% / 속도 +4%'},{count:7,atk:.18,hp:.20,speed:.05,text:'7세트 · 공격 +18% / HP +20% / 속도 +5%'}]},
 eternal:{name:'영겁의 창조자',prefix:'eternal',bonuses:[{count:3,atk:.19,hp:.22,text:'3세트 · 공격 +19% / HP +22%'},{count:5,def:.22,mp:.20,text:'5세트 · 방어 +22% / MP +20%'},{count:7,atk:.25,hp:.25,speed:.07,text:'7세트 · 공격 +25% / HP +25% / 속도 +7%'}]}
};
export function setBonuses(s){const ids=Object.values(s?.equipment||{}),rows=[];for(const [key,set] of Object.entries(MYTHIC_SETS)){const count=ids.filter(id=>String(id||'').startsWith(set.prefix)).length,active=set.bonuses.filter(b=>count>=b.count);if(count||active.length)rows.push({key,name:set.name,count,total:7,active});}return rows;}
export const CONQUEST_CAP=100;
export const conquestNeed=level=>Math.round(60+Math.max(0,level)*24+Math.pow(Math.max(0,level),1.35)*5);
export function conquestTitle(level){const n=Math.max(0,Math.floor(Number(level)||0));return n>=100?'영겁의 정복신':n>=80?'천계 개벽자':n>=60?'월식 추적자':n>=50?'태초 정복자':n>=40?'신격 추적자':n>=30?'공허 지배자':n>=20?'심연 개척자':n>=10?'균열 사냥꾼':'정복 견습생';}
function setStats(s){const out={atk:0,def:0,hp:0,mp:0,speed:0};for(const set of setBonuses(s))for(const b of set.active){for(const k of Object.keys(out))out[k]+=Number(b[k]||0);}return out;}
export function profile(raw={},job='warrior'){
 const s=normalize(raw);s.version=7;s.level=Math.min(LEVEL_CAP,Math.max(1,Math.floor(Number(raw.level)||1)));s.exp=Math.min(1000000000,Math.max(0,Math.floor(Number(raw.exp)||0)));while(s.exp>=MMO_XP(s.level)&&s.level<LEVEL_CAP){s.exp-=MMO_XP(s.level);s.level++;}s.job=Object.hasOwn(JOBS,raw.job)?raw.job:job;s.rank=Math.min(6,Math.max(0,Math.floor(Number(raw.rank)||0)));
 s.zone=['surface','grove','cave','ruins','abyss','celestial','void','origin','rift','eclipse','sanctum'].includes(raw.zone)?raw.zone:'surface';s.materials={};for(const key of ['wood','stone','ore','crystal','stardust'])s.materials[key]=Math.min(100000,Math.max(0,Math.floor(Number(raw.materials?.[key])||0)));
 s.daily=raw.daily&&typeof raw.daily==='object'?{day:String(raw.daily.day||'').slice(0,10),hunt:Math.min(20,Math.max(0,Number(raw.daily.hunt)||0)),gather:Math.min(12,Math.max(0,Number(raw.daily.gather)||0)),dungeon:Math.min(5,Math.max(0,Number(raw.daily.dungeon)||0)),claimed:Array.isArray(raw.daily.claimed)?raw.daily.claimed.filter(x=>['hunt','gather','dungeon'].includes(x)):[]}:null;
 s.partyDungeonDay=/^\d{4}-\d{2}-\d{2}$/.test(String(raw.partyDungeonDay||''))?String(raw.partyDungeonDay):'';s.partyDungeonClears=Math.min(9999,Math.max(0,Math.floor(Number(raw.partyDungeonClears)||0)));s.bossClaims=Array.isArray(raw.bossClaims)?raw.bossClaims.filter(x=>typeof x==='string').slice(-12):[];s.gatherTimes=raw.gatherTimes&&typeof raw.gatherTimes==='object'?raw.gatherTimes:{};s.pvpWins=Math.max(0,Math.floor(Number(raw.pvpWins)||0));
 s.bossKills=Math.max(0,Math.floor(Number(raw.bossKills)||0));s.endgame={mastery:Math.max(0,Math.min(CONQUEST_CAP,Math.floor(Number(raw.endgame?.mastery)||0))),xp:Math.max(0,Math.floor(Number(raw.endgame?.xp)||0)),tokens:Math.max(0,Math.min(99999,Math.floor(Number(raw.endgame?.tokens)||0))),day:String(raw.endgame?.day||'').slice(0,10),hunt:Math.max(0,Math.floor(Number(raw.endgame?.hunt)||0)),elite:Math.max(0,Math.floor(Number(raw.endgame?.elite)||0)),boss:Math.max(0,Math.floor(Number(raw.endgame?.boss)||0)),claimed:Array.isArray(raw.endgame?.claimed)?raw.endgame.claimed.filter(x=>['hunt','elite','boss'].includes(x)):[],pity:{void:Math.max(0,Math.min(5,Math.floor(Number(raw.endgame?.pity?.void)||0))),origin:Math.max(0,Math.min(5,Math.floor(Number(raw.endgame?.pity?.origin)||0)))}};s.originStory={stage:Math.max(0,Math.min(5,Math.floor(Number(raw.originStory?.stage)||0))),kills:Math.max(0,Math.floor(Number(raw.originStory?.kills)||0)),elites:Math.max(0,Math.floor(Number(raw.originStory?.elites)||0)),boss:Math.max(0,Math.floor(Number(raw.originStory?.boss)||0)),claimed:!!raw.originStory?.claimed};s.promotionMaterials={voidSeal:Math.min(9999,Math.max(0,Math.floor(Number(raw.promotionMaterials?.voidSeal)||0))),originMark:Math.min(9999,Math.max(0,Math.floor(Number(raw.promotionMaterials?.originMark)||0))),riftCore:Math.min(9999,Math.max(0,Math.floor(Number(raw.promotionMaterials?.riftCore)||0))),eclipseSigil:Math.min(9999,Math.max(0,Math.floor(Number(raw.promotionMaterials?.eclipseSigil)||0)))};s.ascensionStories={};for(const chapter of ['rift','eclipse']){const q=raw.ascensionStories?.[chapter]||{};s.ascensionStories[chapter]={stage:Math.max(0,Math.min(5,Math.floor(Number(q.stage)||0))),kills:Math.max(0,Math.floor(Number(q.kills)||0)),elites:Math.max(0,Math.floor(Number(q.elites)||0)),boss:Math.max(0,Math.floor(Number(q.boss)||0)),claimed:!!q.claimed};};s.skillUnlocks=Array.isArray(raw.skillUnlocks)?[...new Set(raw.skillUnlocks.filter(x=>/^(warrior|rogue|mage|healer):(3|4|5|6)$/.test(String(x))))]:[];s.manaPotions=Math.min(9999,Math.max(0,Number.isFinite(Number(raw.manaPotions))?Math.floor(Number(raw.manaPotions)):3));s.autoHpPct=[0,30,50,70].includes(Number(raw.autoHpPct))?Number(raw.autoHpPct):0;s.autoMpPct=[0,30,50,70].includes(Number(raw.autoMpPct))?Number(raw.autoMpPct):0;s.bag=Array.isArray(raw.bag)?raw.bag.filter(id=>Object.hasOwn(ITEMS,id)).slice(0,80):['training'];s.enhanceStones=Math.min(9999,Math.max(0,Math.floor(Number(raw.enhanceStones)||0)));s.shiningStones=Math.min(9999,Math.max(0,Math.floor(Number(raw.shiningStones)||0)));s.enhancements={};for(const [id,n] of Object.entries(raw.enhancements||{}))if(Object.hasOwn(ITEMS,id))s.enhancements[id]=Math.max(0,Math.min(MAX_ENHANCE,Math.floor(Number(n)||0)));
 if(!s.bag.includes('training'))s.bag.unshift('training');if(s.weapon&&!s.bag.includes('glowing'))s.bag.push('glowing');
 s.equipment={weapon:s.weapon?'glowing':'training'};for(const [slot,id] of Object.entries(raw.equipment||{}))if(SLOTS[slot]&&ITEMS[id]?.slot===slot&&s.bag.includes(id))s.equipment[slot]=id;
 const st=stats(s),rawMp=Number(raw.mp);s.hp=Math.min(Math.max(1,Number(raw.hp)||MMO_HP(s.level)),st.hp);s.mp=Math.min(st.mp,Math.max(0,Number.isFinite(rawMp)?rawMp:st.mp));return s;
}
export function stats(s){const job=JOBS[s.job]||JOBS.warrior,rank=Math.max(0,Math.min(6,Math.floor(Number(s.rank)||0)));let atk=10+s.level*3+job.attack,def=job.def+Math.floor(s.level*.35),hp=MMO_HP(s.level),mp=job.mana+s.level*5,speed=job.speed+Math.min(.2,Math.max(0,s.level-1)*.001),range=job.range;for(const id of Object.values(s.equipment||{})){const item=ITEMS[id];if(item){const enhance=enhancementLevel(s,id),factor=enhanceMultiplier(enhance);atk+=Math.round((item.atk||0)*factor);def+=Math.round((item.def||0)*factor);hp+=Math.round((item.hp||0)*factor);speed+=(item.speed||0)*(1+enhance*.04);}}const promotion=[1,1.10,1.18,1.28,1.40,1.54,1.72][rank]||1;atk=Math.round(atk*promotion);def=Math.round(def*promotion);hp=Math.round(hp*promotion);mp=Math.round(mp*(1+rank*.05));if(s.job==='warrior'){def=Math.round(def*(1+rank*.025));hp=Math.round(hp*(1+rank*.025));}else if(s.job==='rogue')speed+=rank*.025;else if(s.job==='mage'){mp=Math.round(mp*(1+rank*.03));range+=rank*12;}else if(s.job==='healer'){mp=Math.round(mp*(1+rank*.04));range+=rank*8;}const set=setStats(s),mastery=Math.max(0,Math.min(CONQUEST_CAP,Math.floor(Number(s.endgame?.mastery)||0))),masteryBonus=mastery*.0025;atk=Math.round(atk*(1+set.atk+masteryBonus));def=Math.round(def*(1+set.def+masteryBonus));hp=Math.round(hp*(1+set.hp+masteryBonus));mp=Math.round(mp*(1+set.mp));speed*=1+set.speed;speed=Math.round(speed*1000)/1000;return {atk,def,hp,mp,speed,range};}
export function basicAttackDelay(s){const job=JOBS[s.job]||JOBS.warrior;return Math.max(.30,job.attackDelay/stats(s).speed);}
export function skillCastDelay(s,skill){const base=Math.max(.25,Number(skill?.[5]?.cast)||.8);return Math.max(.28,base/stats(s).speed);}
export function skillMpCost(s,skill){if(!skill)return 0;const spec=skill[5]||{},st=stats(s),fixed=Math.max(0,Number(spec.mp)||0),pct=Math.max(0,Number(spec.mpPct)||0);return Math.max(fixed,Math.round(st.mp*pct));}
export function promotionSkillKey(job,rank){return String(job)+':'+Math.max(0,Math.floor(Number(rank)||0));}
export function promotionSkillLearned(s,rank,job=s?.job){rank=Math.max(0,Math.floor(Number(rank)||0));return rank<3||!!s?.skillUnlocks?.includes(promotionSkillKey(job,rank));}
export function jobName(s){const job=JOBS[s.job]||JOBS.warrior,rank=Math.max(0,Math.min(6,Math.floor(Number(s.rank)||0))),name=job.rankTitles?.[rank]||job.name;return name+(rank?' · '+rank+'차':'');}
export function gainXp(s,xp){s.exp+=xp;const before=s.level;while(s.exp>=MMO_XP(s.level)&&s.level<LEVEL_CAP){s.exp-=MMO_XP(s.level);s.level++;}if(s.level>before){const st=stats(s);s.hp=st.hp;s.mp=st.mp;}return s.level>before;}
export function rollLoot(boss,random=Math.random){const r=random();if(boss){if(r<.10)return RARE_POOL[Math.min(5,Math.floor(random()*6))];if(r<.40)return UNCOMMON_POOL[Math.min(3,Math.floor(random()*4))];}else if(r<.03)return UNCOMMON_POOL[Math.min(3,Math.floor(random()*4))];return null;}
export function equip(s,id){if(!Object.hasOwn(ITEMS,id)||!s.bag.includes(id)||s.level<(ITEMS[id].level||1))return false;s.equipment[ITEMS[id].slot]=id;s.hp=Math.min(s.hp,stats(s).hp);return true;}
export function claim(s){if(s.quest==='ready'){s.gold+=200;s.potions+=3;gainXp(s,80);s.quest='complete';return true;}if(s.quest==='bossReady'){s.gold+=500;gainXp(s,180);s.weapon=1;if(!s.bag.includes('glowing'))s.bag.push('glowing');s.equipment.weapon='glowing';s.quest='groveIntro';s.questKills=0;s.questBoss=0;return true;}const next={groveIntro:'groveHunt',caveIntro:'caveHunt',ruinsIntro:'ruinsHunt',abyssIntro:'abyssHunt',celestialIntro:'celestialHunt'}[s.quest];if(next){s.quest=next;s.questKills=0;s.questBoss=0;return true;}return false;}
