import {W,H,clamp,distance,walkable,pathfind} from './core.js';
import {JOBS,ITEMS,SLOTS,profile,stats,jobName,BUILD,needXp} from './catalog.js?v=20261006-mmo-3';
import {mergeSnapshot} from './network.js';
import {MATERIALS,RECIPES,ZONES,DAILY_TASKS,PROMOTIONS,CHANNEL_CAP,LEVEL_CAP} from './mmo-data.js';
import {API_URL} from './config.js';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const apiBase=location.hostname==='junja-adventure-preview.onrender.com'?API_URL:'';
let wireSnapshot=null;
let token='',connectionKey='',legacy=null,roster=[],selectedSlot=0,state=profile(),view={x:768,y:355},connected=false,paused=false,serverNow=0,receivedAt=0,last=0,clock=0,lastSend=0,movePending=false,streamController=null,streamGeneration=0;
let path=[],selected=null,auto=false,cam={x:0,y:0},scale=1,face=0,flip=false,attackUntil=0,nearNpc=null,npcIntent=null,gesture=null,stick={x:0,y:0};
let systems={nodes:[],bosses:[],trade:null,duel:null,daily:null},gatherIntent=null,mmoPanel='';const resourceEls=new Map();
const keys=new Set(),enemies=new Map(),peers=new Map(),seenEvents=new Set(),npcs=[{id:'elder',x:580,y:330},{id:'merchant',x:1000,y:330}];
try{token=localStorage.getItem('junja-online-token')||'';const old=localStorage.getItem('junja-adventure-play-v2');if(old)legacy=JSON.parse(old);}catch{}
if(legacy)$('legacyRow').hidden=false;
const artReady=Promise.all(['hero','rogue','mage','healer','world','npcs','squirrel','monster-atlas'].map(name=>new Promise((resolve,reject)=>{const im=new Image();im.onload=resolve;im.onerror=()=>reject(Error('캐릭터 이미지를 불러오지 못했어요. 다시 연결해 주세요.'));im.src='./assets/'+name+'.png';})));artReady.catch(()=>{});
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function now(){return serverNow+(performance.now()-receivedAt)/1000;}
async function api(route,data){const r=await fetch(apiBase+'/api/'+route,{method:data?'POST':'GET',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{}),...(connectionKey?{'x-adventure-connection':connectionKey}:{})},body:data?JSON.stringify(data):undefined});const json=await r.json();if(!r.ok)throw Error(json.error||'연결을 확인하세요.');return json;}
let commandChain=Promise.resolve();function command(data){const task=commandChain.then(async()=>{if(!connected)return;try{await api('action',data);}catch(e){toast(e.message);}});commandChain=task.catch(()=>{});return task;}
function stopMovement(){keys.clear();stick={x:0,y:0};path=[];gesture=null;$('joystick').hidden=true;if(connected)command({type:'move',x:0,y:0,manual:true});}
function go(x,y){
 path=pathfind(view,{x,y});
 command({type:'navigate',x,y});
 $('marker').style.left=x+'px';$('marker').style.top=y+'px';$('marker').classList.remove('show');void $('marker').offsetWidth;$('marker').classList.add('show');
}
function camera(force=false,dt=.016){const vw=$('viewport').clientWidth/scale,vh=$('viewport').clientHeight/scale;const x=clamp(view.x-vw*.5,Math.min(0,(W-vw)/2),Math.max(0,W-vw)),y=clamp(view.y-vh*.53,Math.min(0,(H-vh)/2),Math.max(0,H-vh)),f=force?1:1-Math.exp(-12*dt);cam.x+=(x-cam.x)*f;cam.y+=(y-cam.y)*f;$('world').style.transform=`scale(${scale}) translate3d(${-cam.x}px,${-cam.y}px,0)`;}
function resize(){scale=innerWidth<600?.85:Math.min(1,innerWidth/1150);camera(true);}
function screenToWorld(x,y){const r=$('viewport').getBoundingClientRect();return {x:(x-r.left)/scale+cam.x,y:(y-r.top)/scale+cam.y};}
function sprite(el,col,row,rows=3,mirror=false){
 el.style.backgroundPosition=`${col*100/3}% ${row*100/(rows-1)}%`;
 el.style.setProperty('--flip',mirror?-1:1);
}
const MOTION={
 idle:{frames:[0],fps:1},
 walk:{frames:[1,0,2,0],fps:11.5},
 attack:{frames:[1,3,3,2,0],fps:15},
};
function motion(el,art,mode,row,mirror,time,phase=0){
 const cfg=MOTION[mode]||MOTION.idle,frames=cfg.frames,idx=Math.min(frames.length-1,Math.floor((time*cfg.fps+phase)%frames.length));
 sprite(art,frames[idx],row,3,mirror);
 el.dataset.motion=mode;
 const wave=Math.sin(time*(mode==='walk'?Math.PI*2*5.75:Math.PI*2*.9)+phase);
 el.style.setProperty('--bob',mode==='walk'?(-2.2-Math.abs(wave)*2.2)+'px':mode==='idle'?(-Math.max(0,wave)*.7)+'px':'0px');
 el.style.setProperty('--lean',mode==='walk'?(wave*1.6)+'deg':mode==='idle'?(wave*.35)+'deg':'0deg');
 el.style.setProperty('--squash',mode==='walk'?(1-Math.abs(wave)*.025):mode==='idle'?(1+wave*.008):1);
}
function attackPose(el,art,row,mirror,started,duration=.38){
 const p=Math.max(0,Math.min(1,(clock-started)/duration));
 let col=0,lean=0,bob=0,weapon=0;
 if(p<.24){col=1;lean=-7*(p/.24);weapon=-55*(p/.24);bob=1;}
 else if(p<.56){const q=(p-.24)/.32;col=3;lean=-7+18*q;weapon=-55+150*q;bob=-2.5*Math.sin(q*Math.PI);}
 else{const q=(p-.56)/.44;col=q<.45?2:0;lean=11*(1-q);weapon=95*(1-q);}
 sprite(art,col,row,3,mirror);el.dataset.motion='attack';
 el.style.setProperty('--bob',bob+'px');el.style.setProperty('--lean',lean+'deg');el.style.setProperty('--squash',p>.24&&p<.56?.965:1);el.style.setProperty('--weapon-angle',weapon+'deg');el.style.setProperty('--attack-power',String(Math.sin(Math.min(1,p/.72)*Math.PI)));
}
function actorArt(el,s){el.style.backgroundImage=`url('./assets/${JOBS[s.job].art}.png')`;}
function decorate(el,s){const eq=s.equipment||{};el.dataset.job=s.job;for(const slot of ['armor','head','weapon','cape','boots'])el.dataset[slot]=ITEMS[eq[slot]]?.tier||0;el.classList.toggle('promoted',!!s.rank);}
function layers(el){if(el.querySelector('.gear-layers'))return;const div=document.createElement('div');div.className='gear-layers';div.innerHTML='<i class="gear-cape"></i><i class="gear-armor"></i><i class="gear-head"></i><i class="gear-boots"></i><i class="gear-weapon"></i>';el.append(div);}
layers($('hero'));
function entity(type){const el=document.createElement('div');el.className='entity '+type;el.innerHTML='<div class="shadow"></div><div class="sprite"></div><b class="entity-name"></b><div class="life"><i></i></div><div class="tell" hidden></div>';return el;}
function updateSnapshot(data){data=mergeSnapshot(wireSnapshot,data);if(!data)return;wireSnapshot=data;if(data.disconnected){connected=false;streamController?.abort();toast(data.disconnected);showSelection();return;}if(!data.self)return;serverNow=data.now;receivedAt=performance.now();const old=state;state=data.self;systems={nodes:data.nodes||[],bosses:data.bosses||[],trade:data.trade,duel:data.duel,daily:data.daily};syncMMO();auto=state.auto;connected=true;
 if(distance(view,state)>165){view={x:state.x,y:state.y};path=[];camera(true);}
 if(auto||state.navMoving){const me=data.players.find(p=>p.id===state.id);if(me){face=me.face;flip=me.flip;if(me.attacking)attackUntil=clock+.2;}}if(old.job!==state.job||old.rank!==state.rank||$('skillbar').childElementCount!==4)makeSkills();actorArt($('heroArt'),state);decorate($('hero'),state);$('hero').querySelector('.entity-name').textContent=state.name+' · '+jobName(state);document.querySelector('.portrait').style.backgroundImage=`url('./assets/${JOBS[state.job].art}.png')`;
 const mobIds=new Set();for(const e of data.enemies){mobIds.add(e.id);let entry=enemies.get(e.id);if(!entry){const el=entity('enemy'+(e.boss?' boss':''));el.querySelector('b').textContent=e.name||'숲 다람쥐';el.addEventListener('pointerdown',ev=>{ev.stopPropagation();select(e.id);});$('enemyLayer').append(el);entry={el,art:el.querySelector('.sprite'),vx:e.x,vy:e.y};enemies.set(e.id,entry);}Object.assign(entry,e);entry.mmo=!!e.named||e.elite||state.zone!=='surface';entry.el.classList.toggle('mmo-monster',entry.mmo);entry.art.style.backgroundImage=entry.mmo?"url('./assets/monster-atlas.png')":'';entry.art.style.backgroundSize=entry.mmo?'400% 400%':'';entry.el.querySelector('b').textContent=(e.name||'숲 다람쥐')+' · Lv.'+(e.level||1);entry.el.classList.toggle('elite',!!e.elite);entry.el.classList.toggle('named',!!e.named);entry.el.classList.toggle('dead',!e.alive);entry.el.querySelector('.life i').style.width=e.hp/e.max*100+'%';entry.el.querySelector('.tell').hidden=!e.tellAt;entry.el.classList.toggle('selected',selected===e.id);}
 for(const [id,e] of enemies)if(!mobIds.has(id)){e.el.remove();enemies.delete(id);}
 const peerIds=new Set();for(const p of data.players){if(p.id===state.id)continue;peerIds.add(p.id);let peer=peers.get(p.id);if(!peer){const el=entity('peer hero');layers(el);$('world').append(el);peer={el,art:el.querySelector('.sprite'),vx:p.x,vy:p.y};peers.set(p.id,peer);}Object.assign(peer,p);actorArt(peer.art,p);decorate(peer.el,p);peer.el.querySelector('b').textContent=p.name+' · '+jobName(p);peer.el.querySelector('.life i').style.width=p.hp/p.maxHp*100+'%';}
 for(const [id,p] of peers)if(!peerIds.has(id)){p.el.remove();peers.delete(id);}
 $('onlineCount').textContent=data.players.length+'명';$('saveStatus').textContent=data.saveStatus==='error'?'저장 재시도 중':data.saveStatus==='pending'?'서버 저장 대기':'계정에 저장됨';
 for(const event of data.events){if(seenEvents.has(event.id))continue;seenEvents.add(event.id);if(event.kind==='chat'){const row=document.createElement('p');row.textContent=event.text;$('chatLog').append(row);while($('chatLog').childElementCount>3)$('chatLog').firstChild.remove();}else{toast(event.text);$('toast').classList.toggle('rare-toast',event.kind==='rare');}}
 if(seenEvents.size>500)[...seenEvents].slice(0,300).forEach(id=>seenEvents.delete(id));hud();
}
async function consumeStream(generation){streamController?.abort();const controller=new AbortController();streamController=controller;
 try{const r=await fetch(apiBase+'/api/events?protocol=2',{headers:{authorization:'Bearer '+token,'x-adventure-connection':connectionKey},signal:controller.signal});if(!r.ok)throw Error('접속이 끊겼습니다.');const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(generation===streamGeneration){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let index;while((index=buffer.indexOf('\n\n'))>=0){const event=buffer.slice(0,index);buffer=buffer.slice(index+2);if(event.startsWith('data: '))updateSnapshot(JSON.parse(event.slice(6)));}}
 }catch(e){if(controller.signal.aborted)return;}
 if(generation!==streamGeneration)return;connected=false;stopMovement();$('saveStatus').textContent='연결 끊김 · 재접속 필요';$('loading').hidden=false;$('authPanel').hidden=true;$('selectPanel').hidden=true;$('retryBtn').hidden=false;$('loadMessage').textContent='연결이 끊겼어요. 기록을 불러와 다시 접속하세요.';
}
async function showSelection(){streamGeneration++;streamController?.abort();connected=false;stopMovement();paused=false;$('modal').hidden=true;$('loading').hidden=false;$('authPanel').hidden=true;$('selectPanel').hidden=true;$('retryBtn').hidden=true;
 try{$('loadMessage').textContent='캐릭터를 준비하고 있어요…';const me=await api('me');await artReady;$('loadMessage').textContent='친구들과 함께하는 준자마을';roster=me.roster;$('welcome').textContent=me.name+' · 캐릭터 선택';$('characterCards').replaceChildren();for(const s of roster){const job=JOBS[s.job],b=document.createElement('button');b.type='button';b.className='character-card';b.dataset.slot=s.slot;b.setAttribute('aria-pressed',String(s.slot===selectedSlot));b.innerHTML=`<span class="character-preview"><img src="./assets/${job.art}.png" alt="${job.name}" decoding="sync"></span><b>${esc(s.rank?job.title:job.name)}</b><small>Lv.${s.level} · ${job.role}</small>`;b.onclick=()=>{selectedSlot=s.slot;document.querySelectorAll('.character-card').forEach(el=>el.setAttribute('aria-pressed',String(Number(el.dataset.slot)===selectedSlot)));};$('characterCards').append(b);}await Promise.all([...$('characterCards').querySelectorAll('img')].map(im=>im.decode()));$('selectPanel').hidden=false;
 }catch(e){token='';try{localStorage.removeItem('junja-online-token');}catch{}$('authPanel').hidden=false;$('selectPanel').hidden=true;$('authMessage').textContent=e.message;}
}
async function login(register=false){if(!$('authForm').reportValidity())return;const username=$('username').value.trim(),password=$('password').value;$('authMessage').textContent='접속 중…';$('loginBtn').disabled=$('registerBtn').disabled=true;
 try{const r=await api(register?'register':'login',{username,password,...(register&&legacy&&$('legacyCheck').checked?{legacy}:{})});token=r.token;try{localStorage.setItem('junja-online-token',token);}catch{}$('password').value='';await showSelection();}catch(e){$('authMessage').textContent=e.message;}finally{$('loginBtn').disabled=$('registerBtn').disabled=false;}
}
$('authForm').onsubmit=e=>{e.preventDefault();login();};$('registerBtn').onclick=()=>login(true);$('switchAccount').onclick=()=>{token='';try{localStorage.removeItem('junja-online-token');}catch{}$('authPanel').hidden=false;$('selectPanel').hidden=true;$('authMessage').textContent='';};
async function join(){$('joinBtn').disabled=true;$('loadMessage').textContent='준자마을에 접속 중…';try{await artReady;const r=await api('join',{slot:selectedSlot,channel:$('channelInput').value.trim()});connectionKey=r.connectionKey;state=r.snapshot.self;view={x:state.x,y:state.y};selected=null;path=[];updateSnapshot(r.snapshot);resize();makeSkills();face=0;flip=false;$('hero').style.left=view.x+'px';$('hero').style.top=view.y+'px';$('hero').style.zIndex=Math.round(view.y);sprite($('heroArt'),0,0);$('loading').hidden=true;last=performance.now();consumeStream(++streamGeneration);toast(state.channel+'에 접속했습니다. 친구에게 같은 채널을 알려 주세요.');}catch(e){$('loadMessage').textContent=e.message;}finally{$('joinBtn').disabled=false;}}
$('joinBtn').onclick=join;$('retryBtn').onclick=showSelection;
function select(id){const e=enemies.get(id);if(!e?.alive)return;selected=id;npcIntent=null;path=[];if(distance(view,e)>stats(state).range*.8)go(e.x,e.y);hud();}
function attack(skill=-1){if(paused||!connected)return;const started=clock;if(systems.duel?.accepted){command({type:'duelAttack',skill});attackUntil=started+.42;$('hero').dataset.attackStarted=String(started);effect(state.job);return;}const ability=JOBS[state.job].skills[skill];if(ability&&['heal','partyHeal','guard','partyGuard'].includes(ability[4])){command({type:'attack',skill});attackUntil=started+.42;$('hero').dataset.attackStarted=String(started);effect(ability[4].toLowerCase().includes('heal')?'heal':'guard');return;}let e=enemies.get(selected);if(!e?.alive)e=[...enemies.values()].filter(e=>e.alive&&distance(view,e)<stats(state).range).sort((a,b)=>distance(a,view)-distance(b,view))[0];if(!e){toast('다람쥐를 선택해 주세요.');return;}selected=e.id;if(distance(state,e)>stats(state).range){go(e.x,e.y);toast('공격 범위까지 이동합니다.');return;}command({type:'attack',skill,target:e.id});attackUntil=started+.42;$('hero').dataset.attackStarted=String(started);face=Math.abs(e.x-view.x)>Math.abs(e.y-view.y)?2:e.y<view.y?1:0;flip=face===2&&e.x<view.x;path=[];if(skill>=0)effect(state.job);hud();}
function effect(kind){const el=document.createElement('div');el.className='skill-effect '+kind;el.style.left=view.x+'px';el.style.top=view.y+'px';$('effects').append(el);setTimeout(()=>el.remove(),650);}
function makeSkills(){$('skillbar').replaceChildren();JOBS[state.job].skills.forEach((s,i)=>{const b=document.createElement('button');b.id='skill'+i;b.innerHTML=`<b>${s[0]}</b><small>Lv.${s[1]}</small>`;b.onclick=()=>attack(i);$('skillbar').append(b);});}
function hud(){const st=stats(state),t=now();$('playerName').textContent=state.name||'준자';$('level').textContent='Lv.'+state.level+' '+jobName(state);$('hpText').textContent=Math.ceil(state.hp)+' / '+st.hp;$('hpBar').style.width=state.hp/st.hp*100+'%';$('expBar').style.width=Math.min(100,state.exp/needXp(state.level)*100)+'%';$('expText').textContent='EXP '+state.exp+' / '+needXp(state.level);$('gold').textContent=state.gold.toLocaleString()+' G';$('zone').textContent=(state.zone==='surface'?(view.y>590?'다람쥐 숲':'준자마을'):ZONES[state.zone].name)+' · '+(state.channel||'');$('potionLabel').textContent=state.potions+'개';$('potionBtn').disabled=!connected||state.potions<=0;
 const quests={available:['작은 다람쥐의 위협','촌장에게 첫 임무를 받아 주세요.','촌장 찾아가기'],active:['작은 다람쥐의 위협',`공동 처치 ${Math.min(10,state.questKills)} / 10 · 200 G, 물약 3개`,'숲으로 이동'],ready:['임무 완료','촌장에게 보상을 받아 주세요.','촌장에게 보고'],complete:['왕꼬리의 흔적','보스 임무를 수락해 주세요.','촌장 찾아가기'],bossActive:['숲의 수호자 왕꼬리','함께 왕꼬리 처치 · 희귀 장비 10%','보스 찾아가기'],bossReady:['보스 임무 완료','빛나는 무기 보상을 받아 주세요.','촌장에게 보고'],done:['준자마을의 수호자','Lv.99 → 1차 전직 · 정예·던전·일일 임무 도전','숲으로 이동']};const q=quests[state.quest];$('questTitle').textContent=q[0];$('questText').textContent=q[1];$('questAction').textContent=q[2];const e=enemies.get(selected);$('targetPanel').hidden=!e?.alive;if(e?.alive){$('targetName').textContent=e.name||'숲 다람쥐';$('targetRange').textContent=Math.round(distance(view,e)/24)+'m';$('targetHp').style.width=e.hp/e.max*100+'%';}
 $('attackBtn').disabled=paused||!connected||t<(systems.duel?.accepted?Math.max(systems.duel.start,systems.duel.next[state.id]||0):(state.nextAttack||0));$('attackLabel').textContent=systems.duel?.accepted?'대련 공격':e?.alive?distance(state,e)>st.range?'접근 후 공격':'공격 가능':'대상 선택';$('autoBtn').setAttribute('aria-pressed',String(auto));$('autoBtn').querySelector('small').textContent=auto?'ON':'OFF';$('contextBtn').hidden=!nearNpc;JOBS[state.job].skills.forEach((s,i)=>{const b=$('skill'+i);if(!b)return;const locked=state.level<s[1]||(i===3&&!state.rank),cd=Math.max(0,(systems.duel?.accepted?(systems.duel.cooldowns[state.id]?.[i]||0):(state.cooldowns?.[i]||0))-t);b.disabled=paused||!connected||locked||cd>0;b.querySelector('small').textContent=locked?(i===3?'승급 필요':'Lv.'+s[1]):cd>0?Math.ceil(cd)+'초':'준비';});
}
function modal(title,body,actions=[]){mmoPanel='';paused=true;stopMovement();$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modalActions').replaceChildren();for(const [label,fn] of actions){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{closeModal();fn();};$('modalActions').append(b);}$('modal').hidden=false;$('modalClose').focus();}
function closeModal(){mmoPanel='';paused=false;$('modal').hidden=true;$('viewport').focus({preventScroll:true});}
function seekNpc(id){selected=null;command({type:'auto',on:false});const n=npcs.find(n=>n.id===id);go(n.x,n.y+60);npcIntent=id;}
function talk(id){if(id==='merchant'){modal('약초 · 장비 상인','<p>물약은 체력의 50%를 회복합니다. 장비는 가방에서 장착하세요.</p><p>보유 '+state.gold.toLocaleString()+' G</p>',[['물약 · 30 G',()=>command({type:'buy',item:'potion'})],['치료 · 20 G',()=>command({type:'buy',item:'heal'})],...['leather','hood','boots','cape'].map(item=>[ITEMS[item].name+' · '+({leather:120,hood:100,boots:80,cape:180})[item]+' G',()=>command({type:'buy',item})]),['제작 공방',craftWindow]]);return;}const lines={available:'다람쥐 10마리를 물리쳐 주겠니? 친구와 함께 공격해도 처치가 인정된단다.',active:'다람쥐 '+state.questKills+' / 10. 친구와 힘을 합쳐 보렴.',ready:'고맙다! 200 G, 경험치 80과 물약 3개를 받아라.',complete:'왕꼬리를 물리쳐라. 참여자마다 희귀 장비를 얻을 기회가 있단다.',bossActive:'왕꼬리에 25 이상의 피해를 주거나 회복으로 지원하면 보상을 받을 수 있단다.',bossReady:'빛나는 무기, 500 G, 경험치 180을 받아라.',done:'99레벨부터 전직에 도전하렴. 정예·던전과 일일 임무로 성장할 수 있단다.'};const actions=[];if(['available','complete','ready','bossReady'].includes(state.quest))actions.push([['ready','bossReady'].includes(state.quest)?'보상 받기':state.quest==='available'?'임무 수락':'보스 임무 수락',()=>command({type:'quest'})]);actions.push(['승급·직업 보기',jobWindow],['일일 임무',dailyWindow],['채집·제작·던전',adventureWindow]);modal('준자마을 촌장','<p>'+lines[state.quest]+'</p>',actions);}
function jobWindow(){const job=JOBS[state.job],desc={hit:'강력한 단일 공격',area:'대상 주변 광역 공격',drain:'공격과 함께 체력 회복',slow:'광역 피해 · 5초 둔화',heal:'가까운 아군 체력 35% 회복',partyHeal:'가까운 아군 체력 60% 회복',guard:'7초 동안 받는 피해 60% 감소',partyGuard:'가까운 아군에게 7초 보호'};const actions=[['촌장 찾아가기',()=>seekNpc('elder')]];if(state.rank<3)actions.push([(state.rank+1)+'차 전직',()=>command({type:'promote'})]);for(const [id,j] of Object.entries(JOBS))if(id!==state.job)actions.push([j.name+'로 변경 · 500 G',()=>command({type:'job',job:id})]);modal('직업 · 승급',`<p>현재 <strong>${jobName(state)}</strong> · Lv.${state.level}</p><p>전직: 99·199·299레벨, 보스 1·5·15회 (${state.bossKills}회). 촌장 가까이에서 전직하면 공격·방어가 증가합니다. 최대 399레벨. 기존 승급 기록은 유지됩니다.</p><p>직업 변경: 10레벨 + 500 G. 성장·장비를 유지합니다.</p>${job.skills.map((s,i)=>`<p><b>${s[0]}</b> · ${i===3?'승급 후':'Lv.'+s[1]} · ${s[2]}초<br>${desc[s[4]]}</p>`).join('')}`,actions);}
function bagWindow(){const st=stats(state),itemText=id=>ITEMS[id]?esc(ITEMS[id].name):'미장착',slots=Object.entries(SLOTS).map(([slot,name])=>`<button class="equip-slot slot-${slot}" data-unequip="${slot}"><small>${name}</small><b class="${ITEMS[state.equipment[slot]]?.rarity||''}">${itemText(state.equipment[slot])}</b></button>`).join('');modal('장비 · 가방',`<div class="paperdoll"><div id="dollActor" class="doll-actor entity hero"><div class="sprite" style="background-image:url('./assets/${JOBS[state.job].art}.png')"></div></div>${slots}</div><div class="combat-stats"><span>공격 <b>${st.atk}</b></span><span>방어 <b>${st.def}</b></span><span>체력 <b>${st.hp}</b></span></div><p>무기·투구·갑옷·망토·신발은 외형에 반영됩니다.</p><div class="bag-items">${[...new Set(state.bag)].map(id=>{const item=ITEMS[id],eq=state.equipment[item.slot]===id;return `<button data-equip="${id}" class="item-card ${item.rarity}"><b>${itemText(id)}</b><small>${SLOTS[item.slot]} · ${item.atk?'공격 +'+item.atk+' ':''}${item.def?'방어 +'+item.def+' ':''}${item.hp?'체력 +'+item.hp:''} · Lv.${item.level||1}</small><span>${eq?'장착 중':'장착'} · ${state.bag.filter(i=>i===id).length}개</span></button>`;}).join('')}</div><p>${Object.entries(MATERIALS).map(([k,n])=>n+' '+state.materials[k]).join(' · ')}</p><p>물약 ${state.potions}개 · 꼬리털 ${state.tails}개 · ${state.gold.toLocaleString()} G</p><p>시간제 네임드: 전설 장비 1% · 참여자마다 독립 추첨. 같은 등장 회차의 보상은 채널을 바꿔도 한 번만 받습니다.</p>`,[['물약 사용',()=>command({type:'potion'})]]);layers($('dollActor'));decorate($('dollActor'),state);document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=async()=>{await command({type:'equip',item:b.dataset.equip});setTimeout(bagWindow,180);});document.querySelectorAll('[data-unequip]').forEach(b=>b.onclick=()=>{if(b.dataset.unequip==='weapon'){toast('다른 무기로 교체하세요.');return;}command({type:'unequip',slot:b.dataset.unequip});closeModal();});}
function onlineWindow(){modal('함께 모험하기',`<p>현재 채널 <b>${esc(state.channel)}</b> · ${peers.size+1}명</p><p>친구에게 주소와 채널 이름을 알려 주세요. 같은 채널에서 이동·몬스터·보스 체력을 공유합니다.</p><p>접속: ${[state.name,...[...peers.values()].map(p=>p.name)].map(esc).join(', ')}</p><p>채널마다 최대 48명. 현재 같은 지역의 접속자입니다. 캐릭터 4종은 각각 기록이 저장됩니다.</p>`,[['초대 링크 복사',async()=>{const url=new URL(location.href);url.searchParams.set('channel',state.channel);try{await navigator.clipboard.writeText(url.href);toast('초대 링크를 복사했습니다.');}catch{modal('초대 링크','<p>'+esc(url.href)+'</p>');}}],['캐릭터·채널 변경',showSelection],['로그아웃',async()=>{await api('logout',{}).catch(()=>{});streamGeneration++;streamController?.abort();connected=false;token='';try{localStorage.removeItem('junja-online-token');}catch{}$('loading').hidden=false;$('selectPanel').hidden=true;$('authPanel').hidden=false;stopMovement();}]]);}
function chatWindow(){modal('채널 채팅','<form id="chatForm"><label>메시지<input id="chatInput" maxlength="100" placeholder="친구에게 한마디" autocomplete="off"></label><button type="submit">보내기</button></form>');$('chatForm').onsubmit=e=>{e.preventDefault();const text=$('chatInput').value;closeModal();command({type:'chat',text});};$('chatInput').focus();}
$('viewport').addEventListener('pointerdown',ev=>{if(paused||!connected||ev.target.closest('button,.enemy,.resource'))return;selected=null;command({type:'auto',on:false});npcIntent=null;const p=screenToWorld(ev.clientX,ev.clientY);go(p.x,p.y);gesture={id:ev.pointerId,x:ev.clientX,y:ev.clientY,drag:false};$('viewport').setPointerCapture(ev.pointerId);});
$('viewport').addEventListener('pointermove',ev=>{if(!gesture||ev.pointerId!==gesture.id)return;const dx=ev.clientX-gesture.x,dy=ev.clientY-gesture.y;if(Math.hypot(dx,dy)>9)gesture.drag=true;if(gesture.drag){path=[];stick={x:dx,y:dy};$('joystick').hidden=false;$('joystick').style.left=gesture.x+'px';$('joystick').style.top=gesture.y+'px';const d=Math.hypot(dx,dy),r=Math.min(27,d);$('joystick').querySelector('i').style.transform=d?`translate(${dx/d*r}px,${dy/d*r}px)`:'none';}});
function release(){gesture=null;stick={x:0,y:0};$('joystick').hidden=true;}for(const event of ['pointerup','pointercancel','lostpointercapture'])$('viewport').addEventListener(event,release);
window.addEventListener('keydown',ev=>{if(ev.target.closest('input,textarea'))return;if(paused){if(ev.key==='Escape')closeModal();return;}const key=ev.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','w','a','s','d'].includes(key)){ev.preventDefault();keys.add(key);path=[];npcIntent=null;if(auto)command({type:'auto',on:false});if(key===' ')attack();}if(['1','2','3','4'].includes(key))attack(Number(key)-1);if(key==='e'&&nearNpc)talk(nearNpc.id);if(key==='q')attack(0);});window.addEventListener('keyup',ev=>keys.delete(ev.key.toLowerCase()));window.addEventListener('blur',stopMovement);document.addEventListener('visibilitychange',()=>{stopMovement();last=performance.now();});window.addEventListener('resize',resize);
for(const n of npcs)$(n.id).onclick=()=>distance(view,n)<115?talk(n.id):seekNpc(n.id);$('contextBtn').onclick=()=>nearNpc&&talk(nearNpc.id);$('attackBtn').onclick=()=>attack();$('potionBtn').onclick=()=>command({type:'potion'});$('autoBtn').onclick=()=>{path=[];npcIntent=null;command({type:'auto',on:!auto});toast(!auto?'자동 사냥 ON · 숲에서 작동':'자동 사냥 OFF');};$('homeBtn').onclick=()=>{stopMovement();selected=null;command({type:'home'});};$('questToggle').onclick=()=>{$('quest').classList.toggle('collapsed');$('questToggle').textContent=$('quest').classList.contains('collapsed')?'+':'−';};$('questAction').onclick=()=>{if(['available','ready','complete','bossReady'].includes(state.quest))seekNpc('elder');else if(state.quest==='bossActive'){const e=[...enemies.values()].find(e=>e.boss);if(e?.alive)select(e.id);else toast('왕꼬리 재출현까지 '+Math.max(0,Math.ceil((e?.respawn||0)-now()))+'초');}else go(768,720);};$('bagBtn').onclick=bagWindow;$('jobBtn').onclick=jobWindow;$('onlineBtn').onclick=onlineWindow;$('chatBtn').onclick=chatWindow;$('helpBtn').onclick=()=>modal('모험 안내','<p>빈 곳 터치로 이동. 화면 어디서든 드래그하면 방향 이동합니다. PC: WASD / 방향키, Space 공격, Q 첫 스킬, 1~4 스킬, E 대화.</p><p>촌장 임무 → 다람쥐 10마리 → 왕꼬리 → 정예·던전 → Lv.99 첫 전직. 직업에 따라 공격 범위·스킬이 달라집니다.</p><p>가방에서 장비를 장착하세요. 보스 보상은 공격하거나 도사 회복으로 지원한 참여자에게 따로 지급됩니다.</p><p>성장은 계정에 저장됩니다. 같은 아이디의 동시 접속은 마지막 접속만 유지됩니다.</p>');$('modalClose').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal();};
let hudAt=0;
function frame(time){const dt=Math.min(.05,(time-last)/1000||.016);last=time;clock+=dt;if(connected){let dx=0,dy=0;if(!paused&&!document.hidden){dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(!dx&&!dy&&Math.hypot(stick.x,stick.y)>5){dx=stick.x;dy=stick.y;}if(!dx&&!dy&&path.length){if(distance(view,path[0])<16)path.shift();if(path.length){dx=path[0].x-view.x;dy=path[0].y-view.y;}}}const len=Math.hypot(dx,dy);if(len){dx/=len;dy/=len;}if(!auto&&clock>=attackUntil&&len){const x=view.x+dx*250*dt,y=view.y+dy*250*dt;if(walkable(x,view.y))view.x=x;if(walkable(view.x,y))view.y=y;face=Math.abs(dx)>Math.abs(dy)?2:dy<0?1:0;flip=face===2&&dx<0;}if(!len||auto){
  const f=1-Math.exp(-11*dt);view.x+=(state.x-view.x)*f;view.y+=(state.y-view.y)*f;
 }else{
  const drift=distance(view,state);
  if(drift>22){const f=1-Math.exp(-(drift>90?6:2.2)*dt);view.x+=(state.x-view.x)*f;view.y+=(state.y-view.y)*f;}
 }
 if(clock-lastSend>=.09&&!movePending){lastSend=clock;movePending=true;api('action',{type:'move',x:dx,y:dy,manual:len>0}).catch(()=>{}).finally(()=>movePending=false);}
 const attacking=clock<attackUntil,hero=$('hero'),heroArt=$('heroArt');
 if(attacking){const started=Number(hero.dataset.attackStarted)||attackUntil-.42;attackPose(hero,heroArt,face,flip,started,.42);}
 else motion(hero,heroArt,len||auto||state.navMoving?'walk':'idle',face,flip,clock);
 hero.style.left=view.x+'px';hero.style.top=view.y+'px';hero.style.zIndex=Math.round(view.y);hero.classList.toggle('attacking',attacking);hero.classList.toggle('guarded',(state.guard||0)>now());
 for(const e of enemies.values()){const f=1-Math.exp(-15*dt);e.vx+=(e.x-e.vx)*f;e.vy+=(e.y-e.vy)*f;e.el.style.left=e.vx+'px';e.el.style.top=e.vy+'px';e.el.style.zIndex=Math.round(e.vy);sprite(e.art,e.tellAt?3:1+Math.floor(clock*7)%2,e.mmo?({stoneking:0,shadowking:1,dragon:2}[e.named]??3):(e.boss?1:0),e.mmo?4:2);}
 for(const p of peers.values()){const f=1-Math.exp(-13*dt);p.vx+=(p.x-p.vx)*f;p.vy+=(p.y-p.vy)*f;p.el.style.left=p.vx+'px';p.el.style.top=p.vy+'px';p.el.style.zIndex=Math.round(p.vy);p.el.classList.toggle('attacking',!!p.attacking);if(p.attacking){if(!p.localAttackStarted||clock-p.localAttackStarted>.55)p.localAttackStarted=clock;attackPose(p.el,p.art,p.face,p.flip,p.localAttackStarted,.42);}else{p.localAttackStarted=0;motion(p.el,p.art,p.moving?'walk':'idle',p.face,p.flip,clock,(Number(String(p.id).slice(-2).replace(/\D/g,''))||0)*.13);}}nearNpc=state.zone==='surface'?npcs.find(n=>distance(view,n)<115)||null:null;if(gatherIntent){const n=systems.nodes.find(n=>n.id===gatherIntent);if(n&&distance(state,n)<95){gatherIntent=null;command({type:'gather',node:n.id});}}if(npcIntent&&nearNpc?.id===npcIntent&&!path.length){const id=npcIntent;npcIntent=null;talk(id);}camera(false,dt);if(clock-hudAt>.1){hud();hudAt=clock;}}
 requestAnimationFrame(frame);}
const invite=new URL(location.href).searchParams.get('channel');if(invite&&/^[A-Za-z0-9가-힣_-]{2,16}$/.test(invite))$('channelInput').value=invite;if(innerWidth<600){$('quest').classList.add('collapsed');$('questToggle').textContent='+';}resize();makeSkills();requestAnimationFrame(frame);if(token)showSelection();
window.__adventure={build:BUILD,snapshot:()=>({...state,systems:structuredClone(systems),connected,paused,auto,selected,peers:[...peers.values()].map(({id,name,x,y,job,equipment})=>({id,name,x,y,job,equipment})),enemies:[...enemies.values()].map(({id,x,y,hp,alive,boss})=>({id,x,y,hp,alive,boss}))})};
function syncMMO(){const dungeon=state.zone!=='surface';$('world').dataset.zone=state.zone;$('elder').hidden=$('merchant').hidden=dungeon;$('portal').textContent=dungeon?ZONES[state.zone].name+' · 모험 메뉴로 귀환':'다람쥐 숲 ↓';const ids=new Set();for(const n of systems.nodes){ids.add(n.id);let el=resourceEls.get(n.id);if(!el){el=document.createElement('button');el.className='resource';el.dataset.node=n.id;el.onclick=e=>{e.stopPropagation();const n=el.node;if(n.readyAt>now()){toast('재생까지 '+Math.ceil(n.readyAt-now())+'초');return;}if(distance(state,n)>100){gatherIntent=n.id;go(n.x,n.y);toast(MATERIALS[n.material]+' 채집 지점으로 이동');}else command({type:'gather',node:n.id});};$('resourceLayer').append(el);resourceEls.set(n.id,el);}el.node=n;el.style.left=n.x+'px';el.style.top=n.y+'px';el.style.zIndex=Math.round(n.y);el.classList.toggle('depleted',n.readyAt>now());el.textContent=({wood:'🌳',stone:'🪨',ore:'⛏',crystal:'💎'})[n.material]+' '+MATERIALS[n.material]+(n.readyAt>now()?' · '+Math.ceil(n.readyAt-now())+'초':' · 채집');}for(const [id,el] of resourceEls)if(!ids.has(id)){el.remove();resourceEls.delete(id);}const active=systems.trade||systems.duel;$('socialAlert').hidden=!active;$('socialAlert').textContent=active?(systems.trade?'거래 요청·진행 확인':'PVP 대련 확인'):'';const d=systems.duel;$('duelHud').hidden=!d?.accepted;if(d?.accepted){const other=d.players.find(id=>id!==state.id);$('duelHud').textContent=(now()<d.start?'대련 시작 '+Math.ceil(d.start-now())+'초':'대련 중')+' · 나 '+d.health[state.id]+' / 상대 '+d.health[other];}if(mmoPanel==='trade')renderTradeSummary();if(mmoPanel==='duel')renderDuelSummary();}
function adventureWindow(){const mats=Object.entries(MATERIALS).map(([k,n])=>n+' '+state.materials[k]).join(' · ');modal('모험 · 채집 · 던전',`<p>Lv.${state.level} / ${LEVEL_CAP} · ${jobName(state)}</p><p>${mats}</p><p>숲의 나무·돌·광석을 눌러 채집하세요. 개인별 재생 시간은 60·90·120초입니다. 던전 수정은 10분마다 채집하고 마수도 20% 확률로 수정을 줍니다.</p><p>일반 몹 30초 · 정예 3분 · 수련 보스 5분 재등장. 정예는 강한 대신 경험치·골드·장비 보상이 높습니다.</p>`,[['일일 임무',dailyWindow],['제작',craftWindow],['네임드 등장 시간',bossWindowUI],...Object.entries(ZONES).map(([id,z])=>[z.name+' · Lv.'+z.level,()=>{gatherIntent=null;command({type:'travel',zone:id});}])]);}
function dailyWindow(){const d=systems.daily||{hunt:0,gather:0,dungeon:0,claimed:[]};modal('일일 임무 · '+(d.day||''),'<p>한국 시간 자정에 갱신됩니다. 임무는 자동 집계하고 촌장 가까이에서 보상받습니다.</p>'+Object.entries(DAILY_TASKS).map(([id,r])=>`<p><b>${r.name}</b> ${d[id]} / ${r.goal} · ${d.claimed.includes(id)?'수령 완료':r.gold+' G, EXP '+(r.xp+state.level*10)}</p>`).join(''),[['촌장 찾아가기',()=>seekNpc('elder')],...Object.entries(DAILY_TASKS).filter(([id,r])=>d[id]>=r.goal&&!d.claimed.includes(id)).map(([id,r])=>[r.name+' 보상 받기',()=>command({type:'dailyClaim',task:id})])]);}
function craftWindow(){modal('제작 공방',`<p>상인 가까이에서 제작합니다. 보유 ${state.gold.toLocaleString()} G</p><p>${Object.entries(MATERIALS).map(([k,n])=>n+' '+state.materials[k]).join(' · ')}</p>`+Object.entries(RECIPES).map(([id,r])=>`<div class="recipe"><b>${esc(r.name)} · Lv.${r.level}</b><p>${Object.entries(r.materials).map(([k,n])=>MATERIALS[k]+' '+state.materials[k]+'/'+n).join(' · ')} · ${r.gold.toLocaleString()} G</p><button data-craft="${id}" ${state.level<r.level||state.gold<r.gold||Object.entries(r.materials).some(([k,n])=>state.materials[k]<n)?'disabled':''}>${esc(r.name)} 제작</button></div>`).join(''),[['상인 찾아가기',()=>seekNpc('merchant')]]);document.querySelectorAll('[data-craft]').forEach(b=>b.onclick=async()=>{await command({type:'craft',recipe:b.dataset.craft});closeModal();});}
function bossWindowUI(){modal('네임드 · 한국 시간',`<p>각 등장 회차는 1시간 동안 열립니다. 처치되면 다음 회차까지 기다립니다. 서버가 쉬고 있어도 해당 시간에 접속하면 등장합니다.</p>${systems.bosses.map(b=>`<div class="recipe"><b>${esc(b.name)} · Lv.${b.level}</b><p>${ZONES[b.zone].name} · ${b.hours.map(h=>String(h).padStart(2,'0')+':00').join(' / ')} · 하루 ${b.hours.length}회</p><p>${b.active?'등장 시간 진행 중':'다음 등장 '+new Date(b.next*1000).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})} · 전설 장비 1%</p></div>`).join('')}<p>유효한 공격·회복 참여자에게 개인별 보상. 같은 회차 보상은 채널 변경·재접속으로 중복 수령할 수 없습니다. 전설 장비는 Lv.99부터 착용합니다.</p>`,[['모험 메뉴',adventureWindow]]);}
function socialWindow(){modal('유저 · PVP · 아이템 거래',`<p>가까운 유저에게 초대하세요. PVP는 상대가 수락한 뒤 3초 후 시작합니다. 마을에서 대련하며 별도 체력 1000을 사용하고 경험치·골드·장비를 잃지 않습니다.</p><p>거래는 같은 지역 220거리 안에서 진행합니다. 장착 중인 장비와 수련·퀘스트 무기는 거래할 수 없습니다.</p><div class="player-list">${[...peers.values()].map(p=>`<div><b>${esc(p.name)} · Lv.${p.level}</b><button data-duel="${esc(p.id)}">PVP 신청</button><button data-trade="${esc(p.id)}">거래 신청</button></div>`).join('')||'같은 지역에 다른 유저가 없습니다.'}</div><p>내 대련 승리 ${state.pvpWins||0}회 · 레벨·장비에 따른 PVP 보너스는 최대 15%로 제한합니다.</p>`,[[systems.trade?'진행 중인 거래':'거래 확인',tradeWindow],[systems.duel?'진행 중인 대련':'대련 확인',duelWindow]]);document.querySelectorAll('[data-duel],[data-trade]').forEach(b=>b.onclick=()=>{command({type:b.dataset.duel?'duelInvite':'tradeInvite',player:b.dataset.duel||b.dataset.trade});closeModal();});}
function offerText(o){return `${(o?.gold||0).toLocaleString()} G · ${(o?.items||[]).map(id=>esc(ITEMS[id].name)).join(', ')||'장비 없음'} · ${Object.entries(o?.materials||{}).filter(([,n])=>n>0).map(([k,n])=>MATERIALS[k]+' '+n).join(', ')||'재료 없음'}`;}
function renderTradeSummary(){const el=$('tradeSummary'),t=systems.trade;if(!el)return;if(!t){el.innerHTML='<p>거래가 종료되었습니다.</p>';return;}const other=t.players.find(id=>id!==state.id);el.innerHTML=`<p>내 제안: ${offerText(t.offers[state.id])}</p><p>상대 제안: ${offerText(t.offers[other])}</p><p>확인 ${t.confirmed.length}/2 · ${t.confirmed.includes(state.id)?'내 최종 확인 완료':'제안을 등록하고 최종 확인하세요.'}</p><p>제안이 바뀌면 양쪽 확인이 취소됩니다. 두 번째 확인 즉시 거래를 저장합니다.</p>`;}
function tradeWindow(){const t=systems.trade;if(!t){toast('진행 중인 거래가 없습니다.');return;}const received=t.from!==state.id&&!t.accepted;const reserved=new Set(Object.values(state.equipment));const items=state.bag.filter(id=>{if(id==='training'||id==='glowing')return false;if(reserved.has(id)){reserved.delete(id);return false;}return true;}).slice(0,80);modal('아이템 거래',`<div id="tradeSummary"></div>${t.accepted?`<form id="tradeForm"><label>보낼 골드<input id="tradeGold" type="number" min="0" max="${state.gold}" step="1" value="${t.offers[state.id].gold}"></label><p>보낼 장비 선택 · 최대 8개</p><div class="trade-items">${items.map((id,i)=>`<label><input type="checkbox" name="tradeItem" value="${id}">${esc(ITEMS[id].name)}</label>`).join('')||'<p>거래 가능한 장비가 없습니다.</p>'}</div>${Object.entries(MATERIALS).map(([k,n])=>`<label>${n} · 보유 ${state.materials[k]}<input data-material="${k}" type="number" min="0" max="${state.materials[k]}" step="1" value="${t.offers[state.id].materials[k]||0}"></label>`).join('')}<button type="submit">거래 제안 등록</button></form>`:'<p>'+ (received?'상대가 거래를 신청했습니다.':'상대의 수락을 기다립니다.')+'</p>'}`,[...(received?[['거래 수락',async()=>{await command({type:'tradeAccept',id:t.id});setTimeout(tradeWindow,250);}]]:[]),...(t.accepted?[['양쪽 제안 최종 확인',()=>command({type:'tradeConfirm',id:t.id})]]:[]),['거래 취소',()=>command({type:'tradeCancel',id:t.id})]]);mmoPanel='trade';renderTradeSummary();if($('tradeForm'))$('tradeForm').onsubmit=async e=>{e.preventDefault();const materials={};document.querySelectorAll('[data-material]').forEach(el=>materials[el.dataset.material]=Number(el.value));await command({type:'tradeOffer',id:t.id,gold:Number($('tradeGold').value),items:[...document.querySelectorAll('[name=tradeItem]:checked')].map(el=>el.value),materials});};}
function renderDuelSummary(){const el=$('duelSummary'),d=systems.duel;if(!el)return;el.textContent=!d?'대련이 종료되었습니다.':d.accepted?'나 '+d.health[state.id]+' · 상대 '+d.health[d.players.find(id=>id!==state.id)]+' · 창을 닫고 공격·스킬 버튼으로 대련하세요.':'상대의 수락을 기다리고 있습니다.';}
function duelWindow(){const d=systems.duel;if(!d){toast('진행 중인 대련이 없습니다.');return;}modal('PVP 대련','<p id="duelSummary"></p><p>별도 체력 1000 · 마을 안에서 전투 · 최대 2분. 상대와 멀어지거나 접속이 끊기면 취소됩니다.</p>',[...(d.from!==state.id&&!d.accepted?[['대련 수락',()=>command({type:'duelAccept',id:d.id})]]:[]),['대련 취소',()=>command({type:'duelCancel',id:d.id})]]);mmoPanel='duel';renderDuelSummary();}
$('adventureBtn').onclick=adventureWindow;$('socialBtn').onclick=socialWindow;$('socialAlert').onclick=()=>systems.trade?tradeWindow():duelWindow();
