import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
class ClassList{constructor(){this.set=new Set();}add(...s){s.forEach(x=>this.set.add(x));}remove(...s){s.forEach(x=>this.set.delete(x));}contains(s){return this.set.has(s);}toggle(s,force){const on=force??!this.set.has(s);on?this.add(s):this.remove(s);return on;}}
class El{constructor(id=''){this.id=id;this.classList=new ClassList();this.style={};this.children=[];this.listeners={};this.hidden=false;this.clientWidth=390;this.clientHeight=844;this.textContent='';}set innerHTML(s){this.html=s;this.parts={};}get innerHTML(){return this.html;}querySelector(s){return (this.parts??={})[s]??=((new El()));}addEventListener(k,f){(this.listeners[k]??=[]).push(f);}append(e){this.children.push(e);}replaceChildren(){this.children=[];}setAttribute(k,v){this[k]=v;}getBoundingClientRect(){return {left:0,top:0};}focus(){}remove(){}closest(){return null;}setPointerCapture(){} }
let frame,now=0;const elements=new Map();const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');for(const m of html.matchAll(/<[^>]+id="([^"]+)"[^>]*>/g)){const el=new El(m[1]);el.hidden=/\bhidden\b/.test(m[0]);elements.set(m[1],el);}
const docListeners={};globalThis.document={getElementById:id=>elements.get(id),createElement:()=>new El(),hidden:false,addEventListener:(k,f)=>docListeners[k]=f};globalThis.window=globalThis;globalThis.innerWidth=390;globalThis.innerHeight=844;const events={};globalThis.addEventListener=(k,f)=>events[k]=f;globalThis.requestAnimationFrame=f=>frame=f;Object.defineProperty(globalThis,'performance',{value:{now:()=>now},configurable:true});const storage=new Map();globalThis.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};globalThis.Image=class{set src(v){queueMicrotask(()=>this.onload());}};
const $=id=>elements.get(id),snap=()=>__adventure.snapshot();const step=seconds=>{for(let i=0;i<seconds*60;i++){now+=1000/60;frame(now);}};const until=(fn,max=30)=>{for(let i=0;i<max*60&&!fn();i++)step(1/60);assert.ok(fn(),'condition not reached: '+JSON.stringify(snap()));};
await import('../app.js');await new Promise(r=>setImmediate(r));
test('real runtime: NPC, touch route, attack timing, loot, quest, boss, gear and reload save',()=>{
 assert.ok($('loading').hidden);$('questAction').onclick();until(()=>snap().paused);$('modalActions').children[0].onclick();assert.equal(snap().quest,'active');$('questAction').onclick();until(()=>snap().y>670);$('autoBtn').onclick();
 for(let i=0;i<180*60&&snap().quest!=='ready';i++){step(1/60);const s=snap();if(s.hp<50&&s.potions>0)$('potionBtn').onclick();if(s.y<590){$('questAction').onclick();step(4);if(!snap().auto)$('autoBtn').onclick();}}
 assert.equal(snap().quest,'ready');assert.ok(snap().kills>=10);$('homeBtn').onclick();$('questAction').onclick();until(()=>snap().paused);const gold=snap().gold;$('modalActions').children[0].onclick();assert.equal(snap().gold,gold+200);assert.equal(snap().quest,'complete');$('questAction').onclick();until(()=>snap().paused);$('modalActions').children[0].onclick();assert.equal(snap().quest,'bossActive');
 $('questAction').onclick();until(()=>snap().y>650);let boss=snap().enemies.find(e=>e.boss);until(()=>Math.hypot(snap().x-boss.x,snap().y-boss.y)<120,10);
 for(let i=0;i<45*60&&snap().quest==='bossActive';i++){step(1/60);const s=snap();if(s.hp<65&&s.potions>0)$('potionBtn').onclick();if(i%35===0)$('attackBtn').onclick();if(i%310===0)$('skillBtn').onclick();}
 assert.equal(snap().quest,'bossReady');$('homeBtn').onclick();$('questAction').onclick();until(()=>snap().paused);$('modalActions').children[0].onclick();assert.equal(snap().quest,'done');assert.equal(snap().weapon,1);$('bagBtn').onclick();assert.ok($('modalBody').innerHTML.includes('빛나는 검'));$('modalClose').onclick();events.pagehide();const saved=JSON.parse(storage.get('junja-adventure-play-v2'));assert.equal(saved.quest,'done');assert.equal(saved.gold,snap().gold);assert.equal(saved.weapon,1);
 console.log('playthrough',JSON.stringify({level:saved.level,kills:saved.kills,quest:saved.quest,gold:saved.gold}));
});
test('touch cancellation clears movement and manual input respects collisions',()=>{const ev={target:{closest:()=>null},clientX:100,clientY:300,pointerId:1};$('viewport').listeners.pointerdown[0](ev);$('viewport').listeners.pointermove[0]({...ev,clientX:140,clientY:350});assert.equal($('joystick').hidden,false);$('viewport').listeners.pointercancel[0]();assert.equal($('joystick').hidden,true);events.keydown({key:'ArrowLeft',preventDefault(){}});step(8);events.keyup({key:'ArrowLeft'});assert.ok(snap().x>=440);});
test('death returns to village without losing XP, gold or quest reward',()=>{$('questAction').onclick();until(()=>snap().y>690);const before=snap();step(100);assert.ok(snap().y<590);assert.equal(snap().gold,before.gold);assert.equal(snap().quest,'done');assert.equal(snap().weapon,1);assert.ok(snap().hp>0);});
test('storage failure is visible and does not crash controls',()=>{localStorage.setItem=()=>{throw new Error('quota');};events.keydown({key:'ArrowRight',preventDefault(){}});step(.3);events.keyup({key:'ArrowRight'});events.pagehide();assert.ok($('saveStatus').textContent.includes('저장 불가'));});
